// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type MonorepoImportOutput = {
    requestInfo: TrpcRequestInfo;
};

export type TrpcRequestInfo = {
    /**
     * The `trpc-accept` header
     */
    accept: 'application/jsonl' | null;
    /**
     * The type of the request
     */
    type: 'query' | 'mutation' | 'subscription' | 'unknown';
    /**
     * If the content type handler has detected that this is a batch call
     */
    isBatchCall: boolean;
    /**
     * The calls being made
     */
    calls: Array<TrpcRequestInfoProcedureCall>;
    /**
     * Connection params when using `httpSubscriptionLink` or `createWSClient`
     */
    connectionParams: {
        [key: string]: string;
    } | null;
    signal: AbortSignal;
    /**
     * The URL of the request if available
     */
    url: Url | null;
};

export type TrpcRequestInfoProcedureCall = {
    path: string;
    /**
     * The index of this call in a batch request.
     */
    batchIndex: number;
};

export type AbortSignal = {
    aborted: boolean;
    reason: unknown;
};

export type Url = {
    hash: string;
    host: string;
    hostname: string;
    href: string;
    origin: string;
    password: string;
    pathname: string;
    port: string;
    protocol: string;
    search: string;
    searchParams: UrlSearchParams;
    username: string;
};

export type UrlSearchParams = {
    size: number;
};

export type LocalNodeModulesImportOutput = {
    diagnostic: Diagnostic;
};

export type Diagnostic = {
    range: Range;
    severity?: 3 | 1 | 2 | 4;
    code?: string | number;
    codeDescription?: CodeDescription;
    source?: string;
    message: string;
    tags?: Array<1 | 2>;
    relatedInformation?: Array<DiagnosticRelatedInformation>;
    data?: unknown;
};

export type Range = {
    start: Position;
    end: Position;
};

export type Position = {
    line: number;
    character: number;
};

export type CodeDescription = {
    href: string;
};

export type DiagnosticRelatedInformation = {
    location: Location;
    message: string;
};

export type Location = {
    uri: string;
    range: Range;
};

export type RootNodeModulesImportOutput = {
    aliasOptions: Array<Alias> | {
        [key: string]: string;
    };
};

export type Alias = {
    find: string | RegExp;
    replacement: string;
    customResolver?: ResolverObject | null;
};

export type RegExp = {
    source: string;
    global: boolean;
    ignoreCase: boolean;
    multiline: boolean;
    lastIndex: number;
    flags: string;
    sticky: boolean;
    unicode: boolean;
    dotAll: boolean;
    hasIndices: boolean;
};

export type ResolverObject = {
    [key: string]: never;
};

export type DefaultErrorShape = {
    message: string;
    code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
    data: DefaultErrorData;
};

export type DefaultErrorData = {
    code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
    httpStatus: number;
    /**
     * Path to the procedure that threw the error
     */
    path?: string;
    /**
     * Stack trace of the error (only in development)
     */
    stack?: string;
};

export type MonorepoImportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/monorepoImport';
};

export type MonorepoImportErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type MonorepoImportError = MonorepoImportErrors[keyof MonorepoImportErrors];

export type MonorepoImportResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: MonorepoImportOutput;
        };
    };
};

export type MonorepoImportResponse = MonorepoImportResponses[keyof MonorepoImportResponses];

export type LocalNodeModulesImportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/localNodeModulesImport';
};

export type LocalNodeModulesImportErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type LocalNodeModulesImportError = LocalNodeModulesImportErrors[keyof LocalNodeModulesImportErrors];

export type LocalNodeModulesImportResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: LocalNodeModulesImportOutput;
        };
    };
};

export type LocalNodeModulesImportResponse = LocalNodeModulesImportResponses[keyof LocalNodeModulesImportResponses];

export type RootNodeModulesImportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rootNodeModulesImport';
};

export type RootNodeModulesImportErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type RootNodeModulesImportError = RootNodeModulesImportErrors[keyof RootNodeModulesImportErrors];

export type RootNodeModulesImportResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: RootNodeModulesImportOutput;
        };
    };
};

export type RootNodeModulesImportResponse = RootNodeModulesImportResponses[keyof RootNodeModulesImportResponses];
