// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type MonorepoImportOutput = {
    requestInfo: TrpcRequestInfo;
};

export type TrpcRequestInfo = {
    /**
     * The `trpc-accept` header
     */
    accept: 'application/jsonl' | null;
    /**
     * The type of the request
     */
    type: 'query' | 'mutation' | 'subscription' | 'unknown';
    /**
     * If the content type handler has detected that this is a batch call
     */
    isBatchCall: boolean;
    /**
     * The calls being made
     */
    calls: Array<TrpcRequestInfoProcedureCall>;
    /**
     * Connection params when using `httpSubscriptionLink` or `createWSClient`
     */
    connectionParams: {
        [key: string]: string;
    } | null;
    signal: AbortSignal;
    /**
     * The URL of the request if available
     */
    url: Url | null;
};

export type TrpcRequestInfoProcedureCall = {
    path: string;
    /**
     * Read the raw input (deduped and memoized)
     */
    getRawInput: {
        [key: string]: unknown;
    };
    /**
     * Get already parsed inputs - won't trigger reading the body or parsing the inputs
     */
    result: {
        [key: string]: unknown;
    };
    /**
     * The procedure being called, `null` if not found
     */
    procedure: AnyQueryProcedure | AnyMutationProcedure | SubscriptionProcedure | LegacyObservableSubscriptionProcedure | null;
    /**
     * The index of this call in a batch request.
     */
    batchIndex: number;
};

export type AnyQueryProcedure = {
    _def: {
        /**
         * These are just types, they can't be used at runtime
         */
        $types: {
            input: unknown;
            output: unknown;
        };
        procedure: true;
        type: 'query';
        meta: unknown;
        experimental_caller: boolean;
        /**
         * The input parsers for the procedure
         */
        inputs: Array<ParserZodEsque | ParserValibotEsque | ParserArkTypeEsque | ParserStandardSchemaEsque | {
            [key: string]: unknown;
        } | ParserMyZodEsque | ParserScaleEsque | ParserSuperstructEsque | ParserYupEsque>;
    };
    meta: unknown;
};

export type ParserZodEsque = {
    _input: unknown;
    _output: unknown;
};

export type ParserValibotEsque = {
    schema: {
        _types?: {
            input: unknown;
            output: unknown;
        };
    };
};

export type ParserArkTypeEsque = {
    inferIn: unknown;
    infer: unknown;
};

export type ParserStandardSchemaEsque = {
    '~standard': Props;
};

export type Props = {
    /**
     * The version number of the standard.
     */
    version: 1;
    /**
     * The vendor name of the schema library.
     */
    vendor: string;
    /**
     * Validates unknown input values.
     */
    validate: {
        [key: string]: unknown;
    };
    types?: Types;
};

export type Types = {
    /**
     * The input type of the schema.
     */
    input: unknown;
    /**
     * The output type of the schema.
     */
    output: unknown;
};

export type ParserMyZodEsque = {
    parse: {
        [key: string]: unknown;
    };
};

export type ParserScaleEsque = {
    assert: {
        [key: string]: unknown;
    };
};

export type ParserSuperstructEsque = {
    create: {
        [key: string]: unknown;
    };
};

export type ParserYupEsque = {
    validateSync: {
        [key: string]: unknown;
    };
};

export type AnyMutationProcedure = {
    _def: {
        /**
         * These are just types, they can't be used at runtime
         */
        $types: {
            input: unknown;
            output: unknown;
        };
        procedure: true;
        type: 'mutation';
        meta: unknown;
        experimental_caller: boolean;
        /**
         * The input parsers for the procedure
         */
        inputs: Array<ParserZodEsque | ParserValibotEsque | ParserArkTypeEsque | ParserStandardSchemaEsque | {
            [key: string]: unknown;
        } | ParserMyZodEsque | ParserScaleEsque | ParserSuperstructEsque | ParserYupEsque>;
    };
    meta: unknown;
};

export type SubscriptionProcedure = {
    _def: {
        /**
         * These are just types, they can't be used at runtime
         */
        $types: {
            input: unknown;
            output: unknown;
        };
        procedure: true;
        type: 'subscription';
        meta: unknown;
        experimental_caller: boolean;
        /**
         * The input parsers for the procedure
         */
        inputs: Array<ParserZodEsque | ParserValibotEsque | ParserArkTypeEsque | ParserStandardSchemaEsque | {
            [key: string]: unknown;
        } | ParserMyZodEsque | ParserScaleEsque | ParserSuperstructEsque | ParserYupEsque>;
    };
    meta: unknown;
};

export type LegacyObservableSubscriptionProcedure = {
    _observable: true;
    _def: {
        /**
         * These are just types, they can't be used at runtime
         */
        $types: {
            input: unknown;
            output: unknown;
        };
        procedure: true;
        type: 'subscription';
        meta: unknown;
        experimental_caller: boolean;
        /**
         * The input parsers for the procedure
         */
        inputs: Array<ParserZodEsque | ParserValibotEsque | ParserArkTypeEsque | ParserStandardSchemaEsque | {
            [key: string]: unknown;
        } | ParserMyZodEsque | ParserScaleEsque | ParserSuperstructEsque | ParserYupEsque>;
    };
    meta: unknown;
};

export type AbortSignal = {
    aborted: boolean;
    onabort: {
        [key: string]: unknown;
    } | null;
    reason: unknown;
    throwIfAborted: {
        [key: string]: unknown;
    };
    addEventListener: {
        [key: string]: unknown;
    };
    removeEventListener: {
        [key: string]: unknown;
    };
    dispatchEvent: {
        [key: string]: unknown;
    };
};

export type Url = {
    hash: string;
    host: string;
    hostname: string;
    href: string;
    toString: {
        [key: string]: unknown;
    };
    origin: string;
    password: string;
    pathname: string;
    port: string;
    protocol: string;
    search: string;
    searchParams: UrlSearchParams;
    username: string;
    toJSON: {
        [key: string]: unknown;
    };
};

export type UrlSearchParams = {
    size: number;
    append: {
        [key: string]: unknown;
    };
    delete: {
        [key: string]: unknown;
    };
    get: {
        [key: string]: unknown;
    };
    getAll: {
        [key: string]: unknown;
    };
    has: {
        [key: string]: unknown;
    };
    set: {
        [key: string]: unknown;
    };
    sort: {
        [key: string]: unknown;
    };
    toString: {
        [key: string]: unknown;
    };
    forEach: {
        [key: string]: unknown;
    };
    entries: {
        [key: string]: unknown;
    };
    keys: {
        [key: string]: unknown;
    };
    values: {
        [key: string]: unknown;
    };
};

export type LocalNodeModulesImportOutput = {
    diagnostic: Diagnostic;
};

export type Diagnostic = {
    range: Range;
    severity?: 3 | 1 | 2 | 4;
    code?: string | number;
    codeDescription?: CodeDescription;
    source?: string;
    message: string;
    tags?: Array<1 | 2>;
    relatedInformation?: Array<DiagnosticRelatedInformation>;
    data?: unknown;
};

export type Range = {
    start: Position;
    end: Position;
};

export type Position = {
    line: number;
    character: number;
};

export type CodeDescription = {
    href: string;
};

export type DiagnosticRelatedInformation = {
    location: Location;
    message: string;
};

export type Location = {
    uri: string;
    range: Range;
};

export type RootNodeModulesImportOutput = {
    aliasOptions: Array<Alias> | {
        [key: string]: string;
    };
};

export type Alias = {
    find: string | RegExp;
    replacement: string;
    customResolver?: {
        [key: string]: unknown;
    } | ResolverObject | null;
};

export type RegExp = {
    exec: {
        [key: string]: unknown;
    };
    test: {
        [key: string]: unknown;
    };
    source: string;
    global: boolean;
    ignoreCase: boolean;
    multiline: boolean;
    lastIndex: number;
    compile: {
        [key: string]: unknown;
    };
    flags: string;
    sticky: boolean;
    unicode: boolean;
    dotAll: boolean;
    hasIndices: boolean;
};

export type ResolverObject = {
    buildStart?: {
        [key: string]: unknown;
    } | {
        handler: {
            [key: string]: unknown;
        };
        order?: 'pre' | 'post';
        sequential?: boolean;
    };
    resolveId: {
        [key: string]: unknown;
    };
};

export type DefaultErrorShape = {
    message: string;
    code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
    data: DefaultErrorData;
};

export type DefaultErrorData = {
    code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
    httpStatus: number;
    /**
     * Path to the procedure that threw the error
     */
    path?: string;
    /**
     * Stack trace of the error (only in development)
     */
    stack?: string;
};

export type MonorepoImportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/monorepoImport';
};

export type MonorepoImportErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type MonorepoImportError = MonorepoImportErrors[keyof MonorepoImportErrors];

export type MonorepoImportResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: MonorepoImportOutput;
        };
    };
};

export type MonorepoImportResponse = MonorepoImportResponses[keyof MonorepoImportResponses];

export type LocalNodeModulesImportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/localNodeModulesImport';
};

export type LocalNodeModulesImportErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type LocalNodeModulesImportError = LocalNodeModulesImportErrors[keyof LocalNodeModulesImportErrors];

export type LocalNodeModulesImportResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: LocalNodeModulesImportOutput;
        };
    };
};

export type LocalNodeModulesImportResponse = LocalNodeModulesImportResponses[keyof LocalNodeModulesImportResponses];

export type RootNodeModulesImportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rootNodeModulesImport';
};

export type RootNodeModulesImportErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type RootNodeModulesImportError = RootNodeModulesImportErrors[keyof RootNodeModulesImportErrors];

export type RootNodeModulesImportResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: RootNodeModulesImportOutput;
        };
    };
};

export type RootNodeModulesImportResponse = RootNodeModulesImportResponses[keyof RootNodeModulesImportResponses];
