export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          background: 'hsla(216, 28%, 7%, 1)',
          color: 'hsla(210, 16%, 80%, 1)',
        }}
      >
        {children}
      </body>
    </html>
  );
}
