export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          background: 'hsla(216, 28%, 7%, 1)',
          color: 'hsla(210, 16%, 80%, 1)',
        }}
      >
        <main
          style={{
            width: '100vw',
            height: '100vh',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            fontSize: '1.1rem',
          }}
        >
          <div
            style={{
              width: '14rem',
              padding: '1rem',
              background: 'hsla(218, 18%, 12%, 1)',
              borderRadius: '0.5rem',
              color: 'hsla(210, 16%, 80%, 1)',
            }}
          >
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
