import { auth } from '~/auth';
import Link from 'next/link';
import { Suspense } from 'react';
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function LoginLogout(props: { forceLoggedOut?: boolean }) {
  const session = props.forceLoggedOut ? null : await auth();

  // make it slow a bit
  await new Promise((resolve) => setTimeout(resolve, 300));

  return (
    <Link
      href={session ? '/api/auth/signout' : '/api/auth/signin'}
      style={{
        color: 'hsla(210, 16%, 80%, 1)',
      }}
    >
      {session ? 'Sign out' : 'Sign in'}
    </Link>
  );
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          background: 'hsla(216, 28%, 7%, 1)',
          color: 'hsla(210, 16%, 80%, 1)',
        }}
      >
        <main
          style={{
            padding: '3rem',
            fontSize: '1.1rem',
            display: 'flex',
            flexDirection: 'column',
            gap: '1rem',
          }}
        >
          <nav
            style={{
              display: 'flex',
              gap: '1rem',
            }}
          >
            <Link
              href="/"
              style={{
                color: 'hsla(210, 16%, 80%, 1)',
              }}
            >
              Home
            </Link>
            <Suspense fallback={<LoginLogout forceLoggedOut />}>
              <LoginLogout />
            </Suspense>
          </nav>
          <div
            style={{
              padding: '1rem',
              background: 'hsla(218, 18%, 12%, 1)',
              borderRadius: '0.5rem',
              color: 'hsla(210, 16%, 80%, 1)',
            }}
          >
            {children}
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
