// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { TsTypesCategoryMapData, TsTypesCategoryMapErrors, TsTypesCategoryMapResponses, TsTypesCommentData, TsTypesCommentErrors, TsTypesCommentResponses, TsTypesFileSystemData, TsTypesFileSystemErrors, TsTypesFileSystemResponses, TsTypesGraphData, TsTypesGraphErrors, TsTypesGraphResponses, TsTypesJsonValueData, TsTypesJsonValueErrors, TsTypesJsonValueResponses, TsTypesLinkedListData, TsTypesLinkedListErrors, TsTypesLinkedListResponses, TsTypesMutualRecursionData, TsTypesMutualRecursionErrors, TsTypesMutualRecursionResponses, TsTypesOrganizationData, TsTypesOrganizationErrors, TsTypesOrganizationResponses, TsTypesTreeData, TsTypesTreeErrors, TsTypesTreeResponses, TsTypesTripleRecursionData, TsTypesTripleRecursionErrors, TsTypesTripleRecursionResponses, ZodTypesCategoryData, ZodTypesCategoryErrors, ZodTypesCategoryResponses, ZodTypesCommentData, ZodTypesCommentErrors, ZodTypesCommentResponses, ZodTypesLinkedListData, ZodTypesLinkedListErrors, ZodTypesLinkedListResponses, ZodTypesTreeNodeData, ZodTypesTreeNodeErrors, ZodTypesTreeNodeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new Sdk()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class TsTypes extends HeyApiClient {
    /**
     * Tree: children is array of self
     */
    public tree<ThrowOnError extends boolean = false>(options?: Options<TsTypesTreeData, ThrowOnError>) {
        return (options?.client ?? this.client).get<TsTypesTreeResponses, TsTypesTreeErrors, ThrowOnError>({ url: '/tsTypes.tree', ...options });
    }
    
    /**
     * Linked list: nullable self-reference
     */
    public linkedList<ThrowOnError extends boolean = false>(options?: Options<TsTypesLinkedListData, ThrowOnError>) {
        return (options?.client ?? this.client).get<TsTypesLinkedListResponses, TsTypesLinkedListErrors, ThrowOnError>({ url: '/tsTypes.linkedList', ...options });
    }
    
    /**
     * Graph: array of self (cyclic)
     */
    public graph<ThrowOnError extends boolean = false>(options?: Options<TsTypesGraphData, ThrowOnError>) {
        return (options?.client ?? this.client).get<TsTypesGraphResponses, TsTypesGraphErrors, ThrowOnError>({ url: '/tsTypes.graph', ...options });
    }
    
    /**
     * Mutual recursion: Person <-> Pet
     */
    public mutualRecursion<ThrowOnError extends boolean = false>(options?: Options<TsTypesMutualRecursionData, ThrowOnError>) {
        return (options?.client ?? this.client).get<TsTypesMutualRecursionResponses, TsTypesMutualRecursionErrors, ThrowOnError>({ url: '/tsTypes.mutualRecursion', ...options });
    }
    
    /**
     * JSON-like recursive union type
     */
    public jsonValue<ThrowOnError extends boolean = false>(options?: Options<TsTypesJsonValueData, ThrowOnError>) {
        return (options?.client ?? this.client).get<TsTypesJsonValueResponses, TsTypesJsonValueErrors, ThrowOnError>({ url: '/tsTypes.jsonValue', ...options });
    }
    
    /**
     * Optional self-reference
     */
    public comment<ThrowOnError extends boolean = false>(options?: Options<TsTypesCommentData, ThrowOnError>) {
        return (options?.client ?? this.client).get<TsTypesCommentResponses, TsTypesCommentErrors, ThrowOnError>({ url: '/tsTypes.comment', ...options });
    }
    
    /**
     * Recursive type nested inside a non-recursive wrapper
     */
    public organization<ThrowOnError extends boolean = false>(options?: Options<TsTypesOrganizationData, ThrowOnError>) {
        return (options?.client ?? this.client).get<TsTypesOrganizationResponses, TsTypesOrganizationErrors, ThrowOnError>({ url: '/tsTypes.organization', ...options });
    }
    
    /**
     * FileSystem with both array and nullable self-reference
     */
    public fileSystem<ThrowOnError extends boolean = false>(options?: Options<TsTypesFileSystemData, ThrowOnError>) {
        return (options?.client ?? this.client).get<TsTypesFileSystemResponses, TsTypesFileSystemErrors, ThrowOnError>({ url: '/tsTypes.fileSystem', ...options });
    }
    
    /**
     * Recursive type through Record
     */
    public categoryMap<ThrowOnError extends boolean = false>(options?: Options<TsTypesCategoryMapData, ThrowOnError>) {
        return (options?.client ?? this.client).get<TsTypesCategoryMapResponses, TsTypesCategoryMapErrors, ThrowOnError>({ url: '/tsTypes.categoryMap', ...options });
    }
    
    /**
     * Triple mutual recursion: A -> B -> C -> A
     */
    public tripleRecursion<ThrowOnError extends boolean = false>(options?: Options<TsTypesTripleRecursionData, ThrowOnError>) {
        return (options?.client ?? this.client).get<TsTypesTripleRecursionResponses, TsTypesTripleRecursionErrors, ThrowOnError>({ url: '/tsTypes.tripleRecursion', ...options });
    }
}

export class ZodTypes extends HeyApiClient {
    /**
     * Zod recursive category tree
     */
    public category<ThrowOnError extends boolean = false>(options: Options<ZodTypesCategoryData, ThrowOnError>) {
        return (options.client ?? this.client).get<ZodTypesCategoryResponses, ZodTypesCategoryErrors, ThrowOnError>({ url: '/zodTypes.category', ...options });
    }
    
    /**
     * Zod recursive tree node
     */
    public treeNode<ThrowOnError extends boolean = false>(options: Options<ZodTypesTreeNodeData, ThrowOnError>) {
        return (options.client ?? this.client).get<ZodTypesTreeNodeResponses, ZodTypesTreeNodeErrors, ThrowOnError>({ url: '/zodTypes.treeNode', ...options });
    }
    
    /**
     * Zod recursive linked list with nullable
     */
    public linkedList<ThrowOnError extends boolean = false>(options: Options<ZodTypesLinkedListData, ThrowOnError>) {
        return (options.client ?? this.client).get<ZodTypesLinkedListResponses, ZodTypesLinkedListErrors, ThrowOnError>({ url: '/zodTypes.linkedList', ...options });
    }
    
    /**
     * Zod recursive comment with optional
     */
    public comment<ThrowOnError extends boolean = false>(options: Options<ZodTypesCommentData, ThrowOnError>) {
        return (options.client ?? this.client).get<ZodTypesCommentResponses, ZodTypesCommentErrors, ThrowOnError>({ url: '/zodTypes.comment', ...options });
    }
}

export class Sdk extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<Sdk>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        Sdk.__registry.set(this, args?.key);
    }
    
    private _tsTypes?: TsTypes;
    get tsTypes(): TsTypes {
        return this._tsTypes ??= new TsTypes({ client: this.client });
    }
    
    private _zodTypes?: ZodTypes;
    get zodTypes(): ZodTypes {
        return this._zodTypes ??= new ZodTypes({ client: this.client });
    }
}
