// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type TreeNode = {
    value: string;
    children: Array<TreeNode>;
};

export type LinkedListNode = {
    value: number;
    next: LinkedListNode | null;
};

export type GraphNode = {
    id: string;
    label: string;
    neighbors: Array<GraphNode>;
};

export type Person = {
    name: string;
    pets: Array<Pet>;
};

export type Pet = {
    name: string;
    owner: Person;
};

export type JsonValue = string | number | Array<JsonValue> | {
    [key: string]: JsonValue;
} | boolean | null;

export type Comment = {
    text: string;
    replies?: Array<Comment>;
};

export type Organization = {
    name: string;
    rootDepartment: Department;
};

export type Department = {
    name: string;
    manager: string;
    subdepartments: Array<Department>;
};

export type FileSystemEntry = {
    name: string;
    entries: Array<FileSystemEntry>;
    parent: FileSystemEntry | null;
};

export type CategoryMap = {
    name: string;
    children: {
        [key: string]: CategoryMap;
    };
};

export type NodeA = {
    value: string;
    toB: NodeB;
};

export type NodeB = {
    value: number;
    toC: NodeC;
};

export type NodeC = {
    value: boolean;
    toA: NodeA | null;
};

export type ZodCategory = {
    name: string;
    createdAt: Date;
    subcategories: Array<ZodCategory>;
};

export type ZodTreeNode = {
    value: string;
    createdAt: Date;
    children: Array<ZodTreeNode>;
};

export type ZodLinkedList = {
    value: number;
    createdAt: Date;
    next: ZodLinkedList | null;
};

export type ZodComment = {
    text: string;
    createdAt: Date;
    replies?: Array<ZodComment>;
};

export type DefaultErrorShape = {
    message: string;
    code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
    data: DefaultErrorData;
};

export type DefaultErrorData = {
    code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
    httpStatus: number;
    /**
     * Path to the procedure that threw the error
     */
    path?: string;
    /**
     * Stack trace of the error (only in development)
     */
    stack?: string;
};

export type TsTypesTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tsTypes.tree';
};

export type TsTypesTreeErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type TsTypesTreeError = TsTypesTreeErrors[keyof TsTypesTreeErrors];

export type TsTypesTreeResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: TreeNode;
        };
    };
};

export type TsTypesTreeResponse = TsTypesTreeResponses[keyof TsTypesTreeResponses];

export type TsTypesLinkedListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tsTypes.linkedList';
};

export type TsTypesLinkedListErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type TsTypesLinkedListError = TsTypesLinkedListErrors[keyof TsTypesLinkedListErrors];

export type TsTypesLinkedListResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: LinkedListNode;
        };
    };
};

export type TsTypesLinkedListResponse = TsTypesLinkedListResponses[keyof TsTypesLinkedListResponses];

export type TsTypesGraphData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tsTypes.graph';
};

export type TsTypesGraphErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type TsTypesGraphError = TsTypesGraphErrors[keyof TsTypesGraphErrors];

export type TsTypesGraphResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: GraphNode;
        };
    };
};

export type TsTypesGraphResponse = TsTypesGraphResponses[keyof TsTypesGraphResponses];

export type TsTypesMutualRecursionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tsTypes.mutualRecursion';
};

export type TsTypesMutualRecursionErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type TsTypesMutualRecursionError = TsTypesMutualRecursionErrors[keyof TsTypesMutualRecursionErrors];

export type TsTypesMutualRecursionResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: Person;
        };
    };
};

export type TsTypesMutualRecursionResponse = TsTypesMutualRecursionResponses[keyof TsTypesMutualRecursionResponses];

export type TsTypesJsonValueData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tsTypes.jsonValue';
};

export type TsTypesJsonValueErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type TsTypesJsonValueError = TsTypesJsonValueErrors[keyof TsTypesJsonValueErrors];

export type TsTypesJsonValueResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                data: JsonValue;
            };
        };
    };
};

export type TsTypesJsonValueResponse = TsTypesJsonValueResponses[keyof TsTypesJsonValueResponses];

export type TsTypesCommentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tsTypes.comment';
};

export type TsTypesCommentErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type TsTypesCommentError = TsTypesCommentErrors[keyof TsTypesCommentErrors];

export type TsTypesCommentResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: Comment;
        };
    };
};

export type TsTypesCommentResponse = TsTypesCommentResponses[keyof TsTypesCommentResponses];

export type TsTypesOrganizationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tsTypes.organization';
};

export type TsTypesOrganizationErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type TsTypesOrganizationError = TsTypesOrganizationErrors[keyof TsTypesOrganizationErrors];

export type TsTypesOrganizationResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: Organization;
        };
    };
};

export type TsTypesOrganizationResponse = TsTypesOrganizationResponses[keyof TsTypesOrganizationResponses];

export type TsTypesFileSystemData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tsTypes.fileSystem';
};

export type TsTypesFileSystemErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type TsTypesFileSystemError = TsTypesFileSystemErrors[keyof TsTypesFileSystemErrors];

export type TsTypesFileSystemResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: FileSystemEntry;
        };
    };
};

export type TsTypesFileSystemResponse = TsTypesFileSystemResponses[keyof TsTypesFileSystemResponses];

export type TsTypesCategoryMapData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tsTypes.categoryMap';
};

export type TsTypesCategoryMapErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type TsTypesCategoryMapError = TsTypesCategoryMapErrors[keyof TsTypesCategoryMapErrors];

export type TsTypesCategoryMapResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: CategoryMap;
        };
    };
};

export type TsTypesCategoryMapResponse = TsTypesCategoryMapResponses[keyof TsTypesCategoryMapResponses];

export type TsTypesTripleRecursionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tsTypes.tripleRecursion';
};

export type TsTypesTripleRecursionErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type TsTypesTripleRecursionError = TsTypesTripleRecursionErrors[keyof TsTypesTripleRecursionErrors];

export type TsTypesTripleRecursionResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: NodeA;
        };
    };
};

export type TsTypesTripleRecursionResponse = TsTypesTripleRecursionResponses[keyof TsTypesTripleRecursionResponses];

export type ZodTypesCategoryData = {
    body?: never;
    path?: never;
    query: {
        input: ZodCategory;
    };
    url: '/zodTypes.category';
};

export type ZodTypesCategoryErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ZodTypesCategoryError = ZodTypesCategoryErrors[keyof ZodTypesCategoryErrors];

export type ZodTypesCategoryResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: ZodCategory;
        };
    };
};

export type ZodTypesCategoryResponse = ZodTypesCategoryResponses[keyof ZodTypesCategoryResponses];

export type ZodTypesTreeNodeData = {
    body?: never;
    path?: never;
    query: {
        input: ZodTreeNode;
    };
    url: '/zodTypes.treeNode';
};

export type ZodTypesTreeNodeErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ZodTypesTreeNodeError = ZodTypesTreeNodeErrors[keyof ZodTypesTreeNodeErrors];

export type ZodTypesTreeNodeResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: ZodTreeNode;
        };
    };
};

export type ZodTypesTreeNodeResponse = ZodTypesTreeNodeResponses[keyof ZodTypesTreeNodeResponses];

export type ZodTypesLinkedListData = {
    body?: never;
    path?: never;
    query: {
        input: ZodLinkedList;
    };
    url: '/zodTypes.linkedList';
};

export type ZodTypesLinkedListErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ZodTypesLinkedListError = ZodTypesLinkedListErrors[keyof ZodTypesLinkedListErrors];

export type ZodTypesLinkedListResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: ZodLinkedList;
        };
    };
};

export type ZodTypesLinkedListResponse = ZodTypesLinkedListResponses[keyof ZodTypesLinkedListResponses];

export type ZodTypesCommentData = {
    body?: never;
    path?: never;
    query: {
        input: ZodComment;
    };
    url: '/zodTypes.comment';
};

export type ZodTypesCommentErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ZodTypesCommentError = ZodTypesCommentErrors[keyof ZodTypesCommentErrors];

export type ZodTypesCommentResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: ZodComment;
        };
    };
};

export type ZodTypesCommentResponse = ZodTypesCommentResponses[keyof ZodTypesCommentResponses];
