// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  blogPosts: create.doc("blogPosts", {"announcing-trpc-10.mdx": () => import("../content/blog/announcing-trpc-10.mdx?collection=blogPosts"), "announcing-trpc-11.mdx": () => import("../content/blog/announcing-trpc-11.mdx?collection=blogPosts"), "hello-world.mdx": () => import("../content/blog/hello-world.mdx?collection=blogPosts"), "new-tanstack-react-query-integration.mdx": () => import("../content/blog/new-tanstack-react-query-integration.mdx?collection=blogPosts"), "tinyrpc-client.mdx": () => import("../content/blog/tinyrpc-client.mdx?collection=blogPosts"), "trpc-actions.mdx": () => import("../content/blog/trpc-actions.mdx?collection=blogPosts"), "typescript-performance-lessons.mdx": () => import("../content/blog/typescript-performance-lessons.mdx?collection=blogPosts"), }),
  docs: create.doc("docs", {"concepts.mdx": () => import("../content/docs/concepts.mdx?collection=docs"), "example-apps.mdx": () => import("../content/docs/example-apps.mdx?collection=docs"), "getting-started.mdx": () => import("../content/docs/getting-started.mdx?collection=docs"), "introduction.mdx": () => import("../content/docs/introduction.mdx?collection=docs"), "quickstart.mdx": () => import("../content/docs/quickstart.mdx?collection=docs"), "videos-and-community-resources.mdx": () => import("../content/docs/videos-and-community-resources.mdx?collection=docs"), "community/awesome-trpc.mdx": () => import("../content/docs/community/awesome-trpc.mdx?collection=docs"), "community/contributing.mdx": () => import("../content/docs/community/contributing.mdx?collection=docs"), "community/love.mdx": () => import("../content/docs/community/love.mdx?collection=docs"), "community/sponsors.mdx": () => import("../content/docs/community/sponsors.mdx?collection=docs"), "further/faq.mdx": () => import("../content/docs/further/faq.mdx?collection=docs"), "migration/migrate-from-v10-to-v11.mdx": () => import("../content/docs/migration/migrate-from-v10-to-v11.mdx?collection=docs"), "client/links/localLink.mdx": () => import("../content/docs/client/links/localLink.mdx?collection=docs"), "client/links/splitLink.mdx": () => import("../content/docs/client/links/splitLink.mdx?collection=docs"), "client/nextjs/introduction.mdx": () => import("../content/docs/client/nextjs/introduction.mdx?collection=docs"), "client/nextjs/setup.mdx": () => import("../content/docs/client/nextjs/setup.mdx?collection=docs"), "client/react/introduction.mdx": () => import("../content/docs/client/react/introduction.mdx?collection=docs"), "client/react/server-components.mdx": () => import("../content/docs/client/react/server-components.mdx?collection=docs"), "client/react/setup.mdx": () => import("../content/docs/client/react/setup.mdx?collection=docs"), "client/react/useUtils.mdx": () => import("../content/docs/client/react/useUtils.mdx?collection=docs"), "client/tanstack-react-query/migrating.mdx": () => import("../content/docs/client/tanstack-react-query/migrating.mdx?collection=docs"), "client/tanstack-react-query/server-components.mdx": () => import("../content/docs/client/tanstack-react-query/server-components.mdx?collection=docs"), "client/tanstack-react-query/setup.mdx": () => import("../content/docs/client/tanstack-react-query/setup.mdx?collection=docs"), "client/tanstack-react-query/usage.mdx": () => import("../content/docs/client/tanstack-react-query/usage.mdx?collection=docs"), "client/vanilla/setup.mdx": () => import("../content/docs/client/vanilla/setup.mdx?collection=docs"), "server/adapters/fetch.mdx": () => import("../content/docs/server/adapters/fetch.mdx?collection=docs"), }),
};
export default browserCollections;