export const sponsors = [
  {
    name: 'Render',
    imgSrc: 'https://avatars.githubusercontent.com/u/36424661?v=4?s=180',
    link: 'https://render.com',
    monthlyPriceInDollars: 1000,
  },
  {
    name: 'Cal.com, Inc.',
    imgSrc: 'https://avatars.githubusercontent.com/u/79145102?v=4?s=180',
    link: 'https://cal.com',
    monthlyPriceInDollars: 1000,
  },
  {
    name: 'Peer Richelsen',
    imgSrc: 'https://avatars.githubusercontent.com/u/8019099?v=4?s=180',
    link: 'https://cal.com/peer',
    monthlyPriceInDollars: 1000,
  },
  {
    name: 'Jason Docton',
    imgSrc: 'https://avatars.githubusercontent.com/u/22589564?v=4?s=150',
    link: 'http://Youarerad.org',
    monthlyPriceInDollars: 500,
  },
  {
    name: 'Ping Labs',
    imgSrc: 'https://avatars.githubusercontent.com/u/89191727?v=4?s=150',
    link: 'https://ping.gg/',
    monthlyPriceInDollars: 500,
  },
  {
    name: 'Newfront',
    imgSrc:
      'https://user-images.githubusercontent.com/36125/130158930-216fa212-5909-4ee1-b4b9-fd5935f51245.png',
    link: 'https://newfront.com',
    monthlyPriceInDollars: 250,
  },
  {
    name: 'Dr. B',
    imgSrc: 'https://avatars.githubusercontent.com/u/77294655?v=4?s=120',
    link: 'https://hidrb.com',
    monthlyPriceInDollars: 250,
  },
  {
    name: 'Ryan Edge',
    imgSrc: 'https://avatars.githubusercontent.com/u/6907797?v=4?s=120',
    link: 'https://github.com/chimon2000',
    monthlyPriceInDollars: 250,
  },
  {
    name: 'Snaplet',
    imgSrc: 'https://avatars.githubusercontent.com/u/69029941?v=4?s=120',
    link: 'https://snaplet.dev',
    monthlyPriceInDollars: 250,
  },
  {
    name: 'Flylance',
    imgSrc: 'https://avatars.githubusercontent.com/u/67534310?v=4?s=100',
    link: 'https://flylance.com',
    monthlyPriceInDollars: 250,
  },
  {
    name: 'Anthony Short',
    imgSrc: 'https://avatars.githubusercontent.com/u/36125?v=4?s=100',
    link: 'https://anthonyshort.me',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://hampuskraft.com',
    imgSrc: 'https://avatars.githubusercontent.com/u/24176136?v=4?s=100',
    name: 'Hampus Kraft',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'http://www.appdome.com',
    imgSrc: 'https://avatars.githubusercontent.com/u/2037064?v=4?s=100',
    name: 'Daniel Yogel',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://samholmes.net',
    imgSrc: 'https://avatars.githubusercontent.com/u/8385528?v=4?s=100',
    name: 'Sam Holmes',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://github.com/jzimmek',
    imgSrc: 'https://avatars.githubusercontent.com/u/40382?v=4?s=100',
    name: 'Jan Zimmek',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'http://t3.gg',
    imgSrc: 'https://avatars.githubusercontent.com/u/6751787?v=4?s=100',
    name: 'Theo Browne',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://maxgreenwald.me',
    imgSrc: 'https://avatars.githubusercontent.com/u/2615374?v=4?s=100',
    name: 'Max Greenwald',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://github.com/alexn-s',
    imgSrc: 'https://avatars.githubusercontent.com/u/60710873?v=4?s=100',
    name: 'Alex Schumacher',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://react-hook-form.com',
    imgSrc: 'https://avatars.githubusercontent.com/u/10513364?v=4?s=100',
    name: 'Bill',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://github.com/chimon2000',
    imgSrc: 'https://avatars.githubusercontent.com/u/6907797?v=4?s=100',
    name: 'Ryan Edge',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://www.illarionvk.com',
    imgSrc: 'https://avatars.githubusercontent.com/u/5012724?v=4?s=100',
    name: 'Illarion Koperski',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'http://abgn.me',
    imgSrc: 'https://avatars.githubusercontent.com/u/19674362?v=4?s=100',
    name: 'Albin Groen',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://timcole.me',
    imgSrc: 'https://avatars.githubusercontent.com/u/6754577?v=4?s=100',
    name: 'Timothy Cole',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://github.com/utevo',
    imgSrc: 'https://avatars.githubusercontent.com/u/29740731?v=4?s=100',
    name: 'Michał Kowieski',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://iamkhan.io',
    imgSrc: 'https://avatars.githubusercontent.com/u/6490268?v=4?s=100',
    name: 'SchlagerKhan',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://yorick.sh',
    imgSrc: 'https://avatars.githubusercontent.com/u/8572133?v=4?s=100',
    name: 'Ethan Clark',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://github.com/nihinihi01',
    imgSrc: 'https://avatars.githubusercontent.com/u/57569287?v=4?s=100',
    name: 'nihinihi01',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://blog.lucasviana.dev',
    imgSrc: 'https://avatars.githubusercontent.com/u/13911440?v=4?s=100',
    name: 'Lucas Viana',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://farazpatankar.com/',
    imgSrc: 'https://avatars.githubusercontent.com/u/10681116?v=4?s=100',
    name: 'Faraz Patankar',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://github.com/okaforcj',
    imgSrc: 'https://avatars.githubusercontent.com/u/34102565?v=4?s=100',
    name: 'okaforcj',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'http://www.ivanbuncic.com',
    imgSrc: 'https://avatars.githubusercontent.com/u/29887111?v=4?s=100',
    name: 'Ivan Buncic',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'http://solberg.is',
    imgSrc: 'https://avatars.githubusercontent.com/u/701?v=4?s=100',
    name: 'Jökull Sólberg Auðunsson',
    monthlyPriceInDollars: 50,
  },
  {
    link: 'https://ixahmedxi.me',
    imgSrc: 'https://avatars.githubusercontent.com/u/20271968?v=4?s=60',
    name: 'Ahmed Elsakaan',
    monthlyPriceInDollars: 50,
  },
];
