packages:
  - 'packages/*'
  - 'examples/*'
  - 'examples/.*/*'
  - 'examples/minimal/*'
  - 'examples/minimal-react/*'
  - 'examples/minimal-react-typesafe-errors/*'
  - 'examples/minimal-content-types/*'
  - 'www'
  - 'www/og-image'
