import { AddressBar } from '~/components/address-bar';
import './styles.css';

export const metadata = {
  title: 'tRPC Next.js App Router',
  description: 'Generated by create next app',
};

export default async function ProductLayout(props: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="[color-scheme:dark]">
      <head />
      <body className="bg-gray-1100 overflow-y-scroll bg-[url('/grid.svg')]">
        {/* <GlobalNav /> */}

        <div>
          <div className="mx-auto max-w-4xl space-y-8 px-2 pt-20 lg:px-8 lg:py-8">
            <div className="bg-vc-border-gradient rounded-lg p-px shadow-lg shadow-black/20">
              <div className="rounded-lg bg-black">
                <AddressBar />
              </div>
            </div>

            <div className="bg-vc-border-gradient rounded-lg p-px shadow-lg shadow-black/20">
              <div className="rounded-lg bg-black p-3.5 lg:p-6">
                {props.children}
              </div>
            </div>

            <div className="bg-vc-border-gradient rounded-lg p-px shadow-lg shadow-black/20">
              <div className="rounded-lg bg-black">
                <Byline />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}

function Byline() {
  return (
    <div className="flex items-center justify-between gap-x-4 p-3.5 lg:px-5 lg:py-3">
      <div className="flex items-center gap-x-1.5">
        <div className="text-sm text-gray-400">By</div>
        <a href="https://vercel.com" title="Vercel">
          <div className="text-gray-100 hover:text-gray-50">Vercel</div>
        </a>
        <span className="mx-1 text-gray-400">-</span>
        <div className="flex items-center gap-1">
          <div className="text-sm text-gray-400">Ported to use</div>
          <a
            href="
          https://trpc.io"
            title="trpc"
          >
            <div className="text-gray-100 hover:text-gray-50">tRPC</div>
          </a>
          <div className="text-sm text-gray-400">for RSC demo purposes</div>
        </div>
      </div>

      <div className="text-sm text-gray-400">
        <a
          className="underline decoration-dotted underline-offset-4 hover:text-gray-400"
          href="https://github.com/vercel/app-playground"
          target="_blank"
          rel="noreferrer"
        >
          View original source
        </a>
        {' or '}
        <a
          className="underline decoration-dotted underline-offset-4 hover:text-gray-400"
          href="https://vercel.com/templates/next.js/app-directory"
          target="_blank"
          rel="noreferrer"
        >
          deploy your own
        </a>
      </div>
    </div>
  );
}
