import { SessionProvider } from 'next-auth/react';
import { AddressBar } from '~/components/address-bar';
import NextAuthProvider from './next-auth-provider';
import './styles.css';

export const metadata = {
  title: 'tRPC Next.js App Router',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NextAuthProvider>
      <html lang="en" className="[color-scheme:dark]">
        <head />
        <body className="overflow-y-scroll bg-gray-1100 bg-[url('/grid.svg')]">
          {/* <GlobalNav /> */}

          <div className="lg:pl-72">
            <div className="mx-auto max-w-4xl space-y-8 px-2 pt-20 lg:py-8 lg:px-8">
              <div className="rounded-lg bg-vc-border-gradient p-px shadow-lg shadow-black/20">
                <div className="rounded-lg bg-black">
                  <AddressBar />
                </div>
              </div>

              <div className="rounded-lg bg-vc-border-gradient p-px shadow-lg shadow-black/20">
                <div className="rounded-lg bg-black p-3.5 lg:p-6">
                  {children}
                </div>
              </div>

              <div className="rounded-lg bg-vc-border-gradient p-px shadow-lg shadow-black/20">
                <div className="rounded-lg bg-black">
                  <Byline />
                </div>
              </div>
            </div>
          </div>
        </body>
      </html>
    </NextAuthProvider>
  );
}

function Byline() {
  return (
    <div className="flex items-center justify-between gap-x-4 p-3.5 lg:px-5 lg:py-3">
      <div className="flex items-center gap-x-1.5">
        <div className="text-sm text-gray-400">By</div>
        <a href="https://vercel.com" title="Vercel">
          <div className="text-gray-100 hover:text-gray-50">Vercel</div>
        </a>
        <span className="text-gray-400 mx-4">-</span>
        <div className="flex items-center gap-1">
          <div className="text-sm text-gray-400">Modifed by</div>
          <a
            href="
          https://trpc.io"
            title="trpc"
          >
            <div className="text-gray-100 hover:text-gray-50">tRPC</div>
          </a>
          <div className="text-sm text-gray-400">for RSC demo purposes</div>
        </div>
      </div>

      <div className="text-sm text-gray-400">
        <a
          className="underline decoration-dotted underline-offset-4 hover:text-gray-400"
          href="https://github.com/vercel/app-playground"
          target="_blank"
          rel="noreferrer"
        >
          View code
        </a>
        {' or '}
        <a
          className="underline decoration-dotted underline-offset-4 hover:text-gray-400"
          href="https://vercel.com/templates/next.js/app-directory"
          target="_blank"
          rel="noreferrer"
        >
          deploy your own
        </a>
      </div>
    </div>
  );
}
