// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type HelloData = {
  body?: never;
  path?: never;
  query: {
    input: {
      name: string;
    };
  };
  url: '/hello';
};

export type HelloErrors = {
  /**
   * Error response
   */
  default: {
    error: {
      data: {
        zodError: Array<{
          message: string;
          path: Array<string | number>;
        }> | null;
        code:
          | 'PARSE_ERROR'
          | 'BAD_REQUEST'
          | 'INTERNAL_SERVER_ERROR'
          | 'NOT_IMPLEMENTED'
          | 'BAD_GATEWAY'
          | 'SERVICE_UNAVAILABLE'
          | 'GATEWAY_TIMEOUT'
          | 'UNAUTHORIZED'
          | 'PAYMENT_REQUIRED'
          | 'FORBIDDEN'
          | 'NOT_FOUND'
          | 'METHOD_NOT_SUPPORTED'
          | 'TIMEOUT'
          | 'CONFLICT'
          | 'PRECONDITION_FAILED'
          | 'PAYLOAD_TOO_LARGE'
          | 'UNSUPPORTED_MEDIA_TYPE'
          | 'UNPROCESSABLE_CONTENT'
          | 'PRECONDITION_REQUIRED'
          | 'TOO_MANY_REQUESTS'
          | 'CLIENT_CLOSED_REQUEST';
        httpStatus: number;
        path?: string;
        stack?: string;
      };
      message: string;
      code:
        | -32700
        | -32600
        | -32603
        | -32001
        | -32002
        | -32003
        | -32004
        | -32005
        | -32008
        | -32009
        | -32012
        | -32013
        | -32015
        | -32022
        | -32028
        | -32029
        | -32099;
    };
  };
};

export type HelloError = HelloErrors[keyof HelloErrors];

export type HelloResponses = {
  /**
   * Successful response
   */
  200: {
    result: {
      data: string;
    };
  };
};

export type HelloResponse = HelloResponses[keyof HelloResponses];
