import { type VoidComponent } from 'solid-js';
import { Head, Link, Meta, Title } from 'solid-start';
import { trpc } from '~/utils/trpc';

const Home: VoidComponent = () => {
  const hello = trpc.example.hello.useQuery(() => ({ name: 'from tRPC' }));
  return (
    <>
      <Head>
        <Title>Create JD App</Title>
        <Meta name="description" content="Generated by create-jd-app" />
        <Link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>{hello.data ?? 'Loading tRPC query'}</p>
      </main>
    </>
  );
};

export default Home;
