name: Setup Workflow
description: Composite action that sets up pnpm
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false
    - uses: actions/setup-node@v6
      with:
        node-version: 22.x
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
      shell: bash
