// This file is auto-generated by @hey-api/openapi-ts

import type { RichMutateResponse, RichQueryResponse } from './types.gen';

export const richQueryResponseTransformer = async (data: any): Promise<RichQueryResponse> => {
    data.result.data.at = new Date(data.result.data.at);
    data.result.data.meta.updatedAt = new Date(data.result.data.meta.updatedAt);
    return data;
};

export const richMutateResponseTransformer = async (data: any): Promise<RichMutateResponse> => {
    data.result.data.at = new Date(data.result.data.at);
    data.result.data.meta.updatedAt = new Date(data.result.data.meta.updatedAt);
    return data;
};
