// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type DefaultErrorShape = {
    message: string;
    code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
    data: DefaultErrorData;
};

export type DefaultErrorData = {
    code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
    httpStatus: number;
    /**
     * Path to the procedure that threw the error
     */
    path?: string;
    /**
     * Stack trace of the error (only in development)
     */
    stack?: string;
};

export type RichQueryData = {
    body?: never;
    path?: never;
    query: {
        input: {
            name: string;
            count: number;
            active: boolean;
            tags: Array<string>;
            at: Date;
            meta: {
                createdBy: string;
                updatedAt: Date;
            };
            items: Array<{
                id: number;
                label: string;
            }>;
        };
    };
    url: '/rich.query';
};

export type RichQueryErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type RichQueryError = RichQueryErrors[keyof RichQueryErrors];

export type RichQueryResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                name: string;
                count: number;
                active: boolean;
                tags: Array<string>;
                at: Date;
                meta: {
                    createdBy: string;
                    updatedAt: Date;
                };
                items: Array<{
                    id: number;
                    label: string;
                }>;
            };
        };
    };
};

export type RichQueryResponse = RichQueryResponses[keyof RichQueryResponses];

export type RichMutateData = {
    body: {
        name: string;
        count: number;
        active: boolean;
        tags: Array<string>;
        at: Date;
        meta: {
            createdBy: string;
            updatedAt: Date;
        };
        items: Array<{
            id: number;
            label: string;
        }>;
    };
    path?: never;
    query?: never;
    url: '/rich.mutate';
};

export type RichMutateErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type RichMutateError = RichMutateErrors[keyof RichMutateErrors];

export type RichMutateResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                name: string;
                count: number;
                active: boolean;
                tags: Array<string>;
                at: Date;
                meta: {
                    createdBy: string;
                    updatedAt: Date;
                };
                items: Array<{
                    id: number;
                    label: string;
                }>;
            };
        };
    };
};

export type RichMutateResponse = RichMutateResponses[keyof RichMutateResponses];

export type BigintData = {
    body?: never;
    path?: never;
    query: {
        input: {
            id: string;
            amount: bigint;
        };
    };
    url: '/bigint';
};

export type BigintErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type BigintError = BigintErrors[keyof BigintErrors];

export type BigintResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                id: string;
                amount: bigint;
            };
        };
    };
};

export type BigintResponse = BigintResponses[keyof BigintResponses];
