/**
 * Refreshes the curated homepage testimonials through Xquik's X (Twitter) API.
 * Set X_TWITTER_SCRAPER_API_KEY, then run `pnpm --filter www tweetwall-pull`.
 */
import 'dotenv/config';
import { writeFileSync } from 'node:fs';
import XTwitterScraper from 'x-twitter-scraper';
import { prepareTweets } from './data';

// These IDs preserve the editorial selection from the former X collection.
const testimonialTweetIds = [
  '1603224872208908288',
  '1573284779419930624',
  '1573391189373751297',
  '1571988844152786946',
  '1572304619468099584',
  '1571922456239284224',
  '1571813946075803648',
  '1569902022769446913',
  '1569588272392990720',
  '1569341560646402051',
  '1569033706131562496',
  '1568983102931832835',
  '1568403847743442944',
  '1567560240882716677',
  '1564249370085957632',
  '1563224903892971520',
  '1562081793863475201',
  '1561712868348796928',
  '1559973266076434434',
] as const;

const main = async (): Promise<void> => {
  const apiKey = process.env.X_TWITTER_SCRAPER_API_KEY;
  if (!apiKey) {
    throw new Error('Set X_TWITTER_SCRAPER_API_KEY before refreshing tweets.');
  }

  const client = new XTwitterScraper({ apiKey });
  const response = await client.x.tweets.list({
    ids: testimonialTweetIds.join(','),
  });
  const tweets = prepareTweets(response.tweets, testimonialTweetIds);
  const serializedTweets = tweets
    .map((tweet) => `  ${JSON.stringify(tweet)},`)
    .join('\n');
  const output = [
    '// Generated by script.ts. Do not edit manually.',
    "import type { TestimonialTweet } from './data';",
    '',
    '// prettier-ignore',
    'export const tweets = [',
    serializedTweets,
    '] satisfies readonly TestimonialTweet[];',
    '',
  ].join('\n');

  writeFileSync(new URL('./script.output.ts', import.meta.url), output);
};

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.stack : String(error);
  process.stderr.write(`${message}\n`);
  process.exitCode = 1;
});
