import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import type { SidebarItemCategoryConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';
import { parseEnv } from './src/utils/env';

const env = parseEnv(process.env);

const typeDoc: SidebarItemCategoryConfig = {
  type: 'category',
  label: 'API Reference (Auto-generated)',
  collapsed: true,
  items: [
    {
      type: 'autogenerated',
      dirName: 'typedoc',
    },
  ],
};

const config: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'tRPC',
      collapsed: false,
      items: [
        'main/introduction',
        'main/quickstart',
        'main/concepts',
        'main/videos-and-community-resources',
        'main/example-apps',
      ],
    },
    {
      type: 'category',
      label: 'Backend Usage',
      collapsed: true,
      items: [
        'server/overview',
        'server/routers',
        'server/procedures',
        'server/context',
        'server/validators',
        'server/middlewares',
        'server/merging-routers',
        {
          type: 'category',
          label: 'Adapters',
          collapsed: true,
          items: [
            'server/adapters',
            'server/adapters/standalone',
            'server/adapters/express',
            'server/adapters/fastify',
            'server/adapters/nextjs',
            'server/adapters/aws-lambda',
            'server/adapters/fetch',
          ],
        },
        'server/server-side-calls',
        'server/authorization',
        'server/error-handling',
        'server/error-formatting',
        'server/data-transformers',
        'server/non-json-content-types',
        'server/metadata',
        'server/caching',
        'server/subscriptions',
        'server/websockets',
      ],
    },
    {
      type: 'category',
      label: 'Client Usage',
      collapsed: true,
      items: [
        'client/overview',
        {
          type: 'category',
          label: 'Vanilla Client',
          collapsed: true,
          items: [
            'client/vanilla/overview',
            'client/vanilla/setup',
            'client/vanilla/infer-types',
            'client/vanilla/aborting-procedure-calls',
          ],
        },
        {
          type: 'category',
          label: 'TanStack React Query (⭐️)',
          collapsed: true,
          items: [
            'client/tanstack-react-query/overview',
            'client/tanstack-react-query/setup',
            'client/tanstack-react-query/usage',
            'client/tanstack-react-query/migrating',
            'client/tanstack-react-query/server-components',
          ],
        },
        {
          type: 'category',
          label: 'React Query Integration (Classic)',
          collapsed: true,
          items: [
            'client/react/overview',
            'client/react/setup',
            'client/react/server-components',
            'client/react/infer-types',
            'client/react/useQuery',
            'client/react/useMutation',
            'client/react/useInfiniteQuery',
            'client/react/useSubscription',
            'client/react/useUtils',
            'client/react/createTRPCQueryUtils',
            'client/react/useQueries',
            'client/react/suspense',
            'client/react/getQueryKey',
            'client/react/aborting-procedure-calls',
            'client/react/disabling-queries',
          ],
        },
        {
          type: 'category',
          label: 'Next.js Integration',
          collapsed: true,
          items: [
            'client/nextjs/overview',
            {
              type: 'category',
              label: 'App Router',
              collapsed: false,
              items: [
                'client/nextjs/app-router/setup',
                'client/nextjs/app-router/server-actions',
              ],
            },
            {
              type: 'category',
              label: 'Pages Router',
              collapsed: true,
              items: [
                'client/nextjs/pages-router/setup',
                'client/nextjs/pages-router/ssr',
                'client/nextjs/pages-router/ssg',
                'client/nextjs/pages-router/server-side-helpers',
                'client/nextjs/pages-router/aborting-procedure-calls',
              ],
            },
            'client/nextjs/starter-projects',
          ],
        },
        {
          type: 'category',
          label: 'Links',
          collapsed: true,
          items: [
            'client/links/overview',
            'client/links/httpLink',
            'client/links/httpBatchLink',
            'client/links/httpBatchStreamLink',
            'client/links/httpSubscriptionLink',
            'client/links/localLink',
            'client/links/wsLink',
            'client/links/splitLink',
            'client/links/loggerLink',
            'client/links/retryLink',
            'client/headers',
            'client/cors',
          ],
        },
        'client/openapi',
      ],
    },
    {
      type: 'category',
      label: 'Community',
      collapsed: true,
      items: [
        'community/awesome-trpc',
        'community/contributing',
        'community/love',
        'community/sponsors',
      ],
    },
    {
      type: 'category',
      label: 'Extra information',
      collapsed: true,
      items: [
        'further/faq',
        'further/rpc',
        'further/further-reading',
        'migration/migrate-from-v10-to-v11',
      ],
    },
    ...(env.TYPEDOC ? [typeDoc] : []),
  ],
};

export default config;
