import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { trpc } from '../trpc/server/server';
import { TRPCProvider, TRPCReactProvider } from '../trpc/trpc-client';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
  }>,
) {
  return (
    <html lang="en">
      <body
        style={{
          fontFamily: inter.style.fontFamily,
        }}
      >
        <TRPCReactProvider>{props.children}</TRPCReactProvider>
      </body>
    </html>
  );
}
