// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { LimitedData, LimitedErrors, LimitedResponses, PlainData, PlainErrors, PlainResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new Sdk()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class Sdk extends HeyApiClient {
    public static readonly __registry: HeyApiRegistry<Sdk> = new HeyApiRegistry<Sdk>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        Sdk.__registry.set(this, args?.key);
    }
    
    /**
     * Uses the router-wide error shape only
     */
    public plain<ThrowOnError extends boolean = false>(options: Options<PlainData, ThrowOnError>): RequestResult<PlainResponses, PlainErrors, ThrowOnError> {
        return (options.client ?? this.client).get<PlainResponses, PlainErrors, ThrowOnError>({ url: '/plain', ...options });
    }
    
    /**
     * Can additionally fail with a rate-limit error
     */
    public limited<ThrowOnError extends boolean = false>(options: Options<LimitedData, ThrowOnError>): RequestResult<LimitedResponses, LimitedErrors, ThrowOnError> {
        return (options.client ?? this.client).post<LimitedResponses, LimitedErrors, ThrowOnError>({
            url: '/limited',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
