// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type PlainData = {
    body?: never;
    path?: never;
    query: {
        input: {
            name: string;
        };
    };
    url: '/plain';
};

export type PlainErrors = {
    /**
     * Error response
     */
    default: {
        error: {
            data: {
                requestId: string;
                code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
                httpStatus: number;
                /**
                 * Path to the procedure that threw the error
                 */
                path?: string;
                /**
                 * Stack trace of the error (only in development)
                 */
                stack?: string;
            };
            message: string;
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
        };
    };
};

export type PlainError = PlainErrors[keyof PlainErrors];

export type PlainResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: string;
        };
    };
};

export type PlainResponse = PlainResponses[keyof PlainResponses];

export type LimitedData = {
    body: {
        message: string;
    };
    path?: never;
    query?: never;
    url: '/limited';
};

export type LimitedErrors = {
    /**
     * Error response
     */
    default: {
        error: {
            data: {
                requestId: string;
                code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
                httpStatus: number;
                /**
                 * Path to the procedure that threw the error
                 */
                path?: string;
                /**
                 * Stack trace of the error (only in development)
                 */
                stack?: string;
            };
            message: string;
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
        } | {
            data: {
                kind: 'RATE_LIMIT';
                retryAfterMs: number;
                code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
                httpStatus: number;
                /**
                 * Path to the procedure that threw the error
                 */
                path?: string;
                /**
                 * Stack trace of the error (only in development)
                 */
                stack?: string;
            };
            message: string;
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
        };
    };
};

export type LimitedError = LimitedErrors[keyof LimitedErrors];

export type LimitedResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                ok: boolean;
            };
        };
    };
};

export type LimitedResponse = LimitedResponses[keyof LimitedResponses];

export type ChainedData = {
    body: {
        message: string;
    };
    path?: never;
    query?: never;
    url: '/chained';
};

export type ChainedErrors = {
    /**
     * Error response
     */
    default: {
        error: {
            data: {
                requestId: string;
                code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
                httpStatus: number;
                /**
                 * Path to the procedure that threw the error
                 */
                path?: string;
                /**
                 * Stack trace of the error (only in development)
                 */
                stack?: string;
            };
            message: string;
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
        } | {
            data: {
                kind: 'RATE_LIMIT';
                retryAfterMs: number;
                code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
                httpStatus: number;
                /**
                 * Path to the procedure that threw the error
                 */
                path?: string;
                /**
                 * Stack trace of the error (only in development)
                 */
                stack?: string;
            };
            message: string;
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
        } | {
            data: {
                kind: 'CONFLICT';
                conflictsWith: string;
                code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
                httpStatus: number;
                /**
                 * Path to the procedure that threw the error
                 */
                path?: string;
                /**
                 * Stack trace of the error (only in development)
                 */
                stack?: string;
            };
            message: string;
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
        };
    };
};

export type ChainedError = ChainedErrors[keyof ChainedErrors];

export type ChainedResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                ok: boolean;
            };
        };
    };
};

export type ChainedResponse = ChainedResponses[keyof ChainedResponses];

export type ChainedDuplicateData = {
    body: {
        message: string;
    };
    path?: never;
    query?: never;
    url: '/chainedDuplicate';
};

export type ChainedDuplicateErrors = {
    /**
     * Error response
     */
    default: {
        error: {
            data: {
                requestId: string;
                code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
                httpStatus: number;
                /**
                 * Path to the procedure that threw the error
                 */
                path?: string;
                /**
                 * Stack trace of the error (only in development)
                 */
                stack?: string;
            };
            message: string;
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
        } | {
            data: {
                kind: 'RATE_LIMIT';
                retryAfterMs: number;
                code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
                httpStatus: number;
                /**
                 * Path to the procedure that threw the error
                 */
                path?: string;
                /**
                 * Stack trace of the error (only in development)
                 */
                stack?: string;
            };
            message: string;
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
        };
    };
};

export type ChainedDuplicateError = ChainedDuplicateErrors[keyof ChainedDuplicateErrors];

export type ChainedDuplicateResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                ok: boolean;
            };
        };
    };
};

export type ChainedDuplicateResponse = ChainedDuplicateResponses[keyof ChainedDuplicateResponses];

export type NeverClaimsData = {
    body: {
        message: string;
    };
    path?: never;
    query?: never;
    url: '/neverClaims';
};

export type NeverClaimsErrors = {
    /**
     * Error response
     */
    default: {
        error: {
            data: {
                requestId: string;
                code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
                httpStatus: number;
                /**
                 * Path to the procedure that threw the error
                 */
                path?: string;
                /**
                 * Stack trace of the error (only in development)
                 */
                stack?: string;
            };
            message: string;
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
        };
    };
};

export type NeverClaimsError = NeverClaimsErrors[keyof NeverClaimsErrors];

export type NeverClaimsResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                ok: boolean;
            };
        };
    };
};

export type NeverClaimsResponse = NeverClaimsResponses[keyof NeverClaimsResponses];

export type MultiShapeData = {
    body: {
        message: string;
    };
    path?: never;
    query?: never;
    url: '/multiShape';
};

export type MultiShapeErrors = {
    /**
     * Error response
     */
    default: {
        error: {
            data: {
                requestId: string;
                code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
                httpStatus: number;
                /**
                 * Path to the procedure that threw the error
                 */
                path?: string;
                /**
                 * Stack trace of the error (only in development)
                 */
                stack?: string;
            };
            message: string;
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
        } | {
            data: {
                kind: 'RATE_LIMIT';
                retryAfterMs: number;
                code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
                httpStatus: number;
                /**
                 * Path to the procedure that threw the error
                 */
                path?: string;
                /**
                 * Stack trace of the error (only in development)
                 */
                stack?: string;
            };
            message: string;
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
        } | {
            data: {
                kind: 'CONFLICT';
                conflictsWith: string;
                code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
                httpStatus: number;
                /**
                 * Path to the procedure that threw the error
                 */
                path?: string;
                /**
                 * Stack trace of the error (only in development)
                 */
                stack?: string;
            };
            message: string;
            code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
        };
    };
};

export type MultiShapeError = MultiShapeErrors[keyof MultiShapeErrors];

export type MultiShapeResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                ok: boolean;
            };
        };
    };
};

export type MultiShapeResponse = MultiShapeResponses[keyof MultiShapeResponses];
