// This file is auto-generated by @hey-api/openapi-ts

import type { ComplexTypesDateTypeResponse, InferredReturnsCreateItemResponse, InferredReturnsDateReturnResponse, RecursiveTypesCategoryResponse, RecursiveTypesLinkedListResponse, RecursiveTypesTreeResponse } from './types.gen';

export const complexTypesDateTypeResponseTransformer = async (data: any): Promise<ComplexTypesDateTypeResponse> => {
    data.result.data.createdAt = new Date(data.result.data.createdAt);
    return data;
};

export const inferredReturnsDateReturnResponseTransformer = async (data: any): Promise<InferredReturnsDateReturnResponse> => {
    data.result.data.createdAt = new Date(data.result.data.createdAt);
    return data;
};

export const inferredReturnsCreateItemResponseTransformer = async (data: any): Promise<InferredReturnsCreateItemResponse> => {
    data.result.data.createdAt = new Date(data.result.data.createdAt);
    return data;
};

const treeNodeSchemaResponseTransformer = (data: any) => {
    data.children = data.children.map((item: any) => treeNodeSchemaResponseTransformer(item));
    return data;
};

export const recursiveTypesTreeResponseTransformer = async (data: any): Promise<RecursiveTypesTreeResponse> => {
    data.result.data = treeNodeSchemaResponseTransformer(data.result.data);
    return data;
};

const linkedListNodeSchemaResponseTransformer = (data: any) => {
    if (data.next) {
        data.next = linkedListNodeSchemaResponseTransformer(data.next);
    }
    return data;
};

export const recursiveTypesLinkedListResponseTransformer = async (data: any): Promise<RecursiveTypesLinkedListResponse> => {
    data.result.data = linkedListNodeSchemaResponseTransformer(data.result.data);
    return data;
};

const categorySchemaResponseTransformer = (data: any) => {
    data.subcategories = data.subcategories.map((item: any) => categorySchemaResponseTransformer(item));
    return data;
};

export const recursiveTypesCategoryResponseTransformer = async (data: any): Promise<RecursiveTypesCategoryResponse> => {
    data.result.data = categorySchemaResponseTransformer(data.result.data);
    return data;
};
