// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type UserProfile = {
    id: number;
    name: string;
    email: string;
};

export type OrderItem = {
    productId: number;
    quantity: number;
    price: number;
};

export type Address = {
    street: string;
    city: string;
    zipCode: string;
};

export type TreeNode = {
    value: string;
    children: Array<TreeNode>;
};

export type LinkedListNode = {
    value: number;
    next: LinkedListNode | null;
};

export type Category = {
    name: string;
    subcategories: Array<Category>;
};

export type DefaultErrorShape = {
    message: string;
    code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
    data: DefaultErrorData;
};

export type DefaultErrorData = {
    code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
    httpStatus: number;
    path?: string;
    stack?: string;
};

export type GreetingData = {
    body?: never;
    path?: never;
    query: {
        input: {
            name: string;
        };
    };
    url: '/greeting';
};

export type GreetingErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type GreetingError = GreetingErrors[keyof GreetingErrors];

export type GreetingResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                message: string;
            };
        };
    };
};

export type GreetingResponse = GreetingResponses[keyof GreetingResponses];

export type NoInputData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/noInput';
};

export type NoInputErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type NoInputError = NoInputErrors[keyof NoInputErrors];

export type NoInputResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: string;
        };
    };
};

export type NoInputResponse = NoInputResponses[keyof NoInputResponses];

export type EchoData = {
    body: string;
    path?: never;
    query?: never;
    url: '/echo';
};

export type EchoErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type EchoError = EchoErrors[keyof EchoErrors];

export type EchoResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: string;
        };
    };
};

export type EchoResponse = EchoResponses[keyof EchoResponses];

export type UserListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user.list';
};

export type UserListErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type UserListError = UserListErrors[keyof UserListErrors];

export type UserListResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: Array<{
                id: number;
                name: string;
            }>;
        };
    };
};

export type UserListResponse = UserListResponses[keyof UserListResponses];

export type UserCreateData = {
    body: {
        name: string;
        age?: number;
    };
    path?: never;
    query?: never;
    url: '/user.create';
};

export type UserCreateErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type UserCreateError = UserCreateErrors[keyof UserCreateErrors];

export type UserCreateResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                name: string;
                age?: number;
                id: number;
            };
        };
    };
};

export type UserCreateResponse = UserCreateResponses[keyof UserCreateResponses];

export type ComplexTypesZodEnumData = {
    body?: never;
    path?: never;
    query: {
        input: {
            status: 'active' | 'inactive' | 'pending';
        };
    };
    url: '/complexTypes.zodEnum';
};

export type ComplexTypesZodEnumErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesZodEnumError = ComplexTypesZodEnumErrors[keyof ComplexTypesZodEnumErrors];

export type ComplexTypesZodEnumResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                status: 'active' | 'inactive' | 'pending';
            };
        };
    };
};

export type ComplexTypesZodEnumResponse = ComplexTypesZodEnumResponses[keyof ComplexTypesZodEnumResponses];

export type ComplexTypesNativeEnumData = {
    body?: never;
    path?: never;
    query: {
        input: {
            direction: 'UP' | 'DOWN' | 'LEFT' | 'RIGHT';
        };
    };
    url: '/complexTypes.nativeEnum';
};

export type ComplexTypesNativeEnumErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesNativeEnumError = ComplexTypesNativeEnumErrors[keyof ComplexTypesNativeEnumErrors];

export type ComplexTypesNativeEnumResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                direction: 'UP' | 'DOWN' | 'LEFT' | 'RIGHT';
            };
        };
    };
};

export type ComplexTypesNativeEnumResponse = ComplexTypesNativeEnumResponses[keyof ComplexTypesNativeEnumResponses];

export type ComplexTypesLiteralData = {
    body?: never;
    path?: never;
    query: {
        input: {
            strLit: 'hello';
            numLit: 42;
            boolLit: true;
        };
    };
    url: '/complexTypes.literal';
};

export type ComplexTypesLiteralErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesLiteralError = ComplexTypesLiteralErrors[keyof ComplexTypesLiteralErrors];

export type ComplexTypesLiteralResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                strLit: 'hello';
                numLit: 42;
                boolLit: true;
            };
        };
    };
};

export type ComplexTypesLiteralResponse = ComplexTypesLiteralResponses[keyof ComplexTypesLiteralResponses];

export type ComplexTypesLiteralUnionData = {
    body?: never;
    path?: never;
    query: {
        input: {
            color: 'red' | 'green' | 'blue';
        };
    };
    url: '/complexTypes.literalUnion';
};

export type ComplexTypesLiteralUnionErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesLiteralUnionError = ComplexTypesLiteralUnionErrors[keyof ComplexTypesLiteralUnionErrors];

export type ComplexTypesLiteralUnionResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                color: 'red' | 'green' | 'blue';
            };
        };
    };
};

export type ComplexTypesLiteralUnionResponse = ComplexTypesLiteralUnionResponses[keyof ComplexTypesLiteralUnionResponses];

export type ComplexTypesDiscriminatedUnionData = {
    body: {
        type: 'text';
        content: string;
    } | {
        type: 'image';
        url: string;
        width: number;
        height: number;
    } | {
        type: 'video';
        url: string;
        duration: number;
    };
    path?: never;
    query?: never;
    url: '/complexTypes.discriminatedUnion';
};

export type ComplexTypesDiscriminatedUnionErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesDiscriminatedUnionError = ComplexTypesDiscriminatedUnionErrors[keyof ComplexTypesDiscriminatedUnionErrors];

export type ComplexTypesDiscriminatedUnionResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                type: 'text';
                content: string;
            } | {
                type: 'image';
                url: string;
                width: number;
                height: number;
            } | {
                type: 'video';
                url: string;
                duration: number;
            };
        };
    };
};

export type ComplexTypesDiscriminatedUnionResponse = ComplexTypesDiscriminatedUnionResponses[keyof ComplexTypesDiscriminatedUnionResponses];

export type ComplexTypesUnionData = {
    body?: never;
    path?: never;
    query: {
        input: {
            value: string | number | boolean;
        };
    };
    url: '/complexTypes.union';
};

export type ComplexTypesUnionErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesUnionError = ComplexTypesUnionErrors[keyof ComplexTypesUnionErrors];

export type ComplexTypesUnionResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                value: string | number | boolean;
            };
        };
    };
};

export type ComplexTypesUnionResponse = ComplexTypesUnionResponses[keyof ComplexTypesUnionResponses];

export type ComplexTypesIntersectionData = {
    body: {
        id: number;
        name: string;
        email: string;
    };
    path?: never;
    query?: never;
    url: '/complexTypes.intersection';
};

export type ComplexTypesIntersectionErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesIntersectionError = ComplexTypesIntersectionErrors[keyof ComplexTypesIntersectionErrors];

export type ComplexTypesIntersectionResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                id: number;
                name: string;
                email: string;
            };
        };
    };
};

export type ComplexTypesIntersectionResponse = ComplexTypesIntersectionResponses[keyof ComplexTypesIntersectionResponses];

export type ComplexTypesTupleData = {
    body?: never;
    path?: never;
    query: {
        input: {
            pair: [
                string,
                number
            ];
            triple: [
                string,
                number,
                boolean
            ];
        };
    };
    url: '/complexTypes.tuple';
};

export type ComplexTypesTupleErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesTupleError = ComplexTypesTupleErrors[keyof ComplexTypesTupleErrors];

export type ComplexTypesTupleResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                pair: [
                    string,
                    number
                ];
                triple: [
                    string,
                    number,
                    boolean
                ];
            };
        };
    };
};

export type ComplexTypesTupleResponse = ComplexTypesTupleResponses[keyof ComplexTypesTupleResponses];

export type ComplexTypesRecordData = {
    body?: never;
    path?: never;
    query: {
        input: {
            metadata: {
                [key: string]: string;
            };
            scores: {
                [key: string]: number;
            };
        };
    };
    url: '/complexTypes.record';
};

export type ComplexTypesRecordErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesRecordError = ComplexTypesRecordErrors[keyof ComplexTypesRecordErrors];

export type ComplexTypesRecordResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                metadata: {
                    [key: string]: string;
                };
                scores: {
                    [key: string]: number;
                };
            };
        };
    };
};

export type ComplexTypesRecordResponse = ComplexTypesRecordResponses[keyof ComplexTypesRecordResponses];

export type ComplexTypesComplexArraysData = {
    body?: never;
    path?: never;
    query: {
        input: {
            tags: Array<string>;
            items: Array<{
                id: number;
                label: string;
                active: boolean;
            }>;
            matrix: Array<Array<number>>;
        };
    };
    url: '/complexTypes.complexArrays';
};

export type ComplexTypesComplexArraysErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesComplexArraysError = ComplexTypesComplexArraysErrors[keyof ComplexTypesComplexArraysErrors];

export type ComplexTypesComplexArraysResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                tags: Array<string>;
                items: Array<{
                    id: number;
                    label: string;
                    active: boolean;
                }>;
                matrix: Array<Array<number>>;
            };
        };
    };
};

export type ComplexTypesComplexArraysResponse = ComplexTypesComplexArraysResponses[keyof ComplexTypesComplexArraysResponses];

export type ComplexTypesDeeplyNestedData = {
    body?: never;
    path?: never;
    query: {
        input: {
            level1: {
                level2: {
                    level3: {
                        value: string;
                    };
                };
            };
        };
    };
    url: '/complexTypes.deeplyNested';
};

export type ComplexTypesDeeplyNestedErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesDeeplyNestedError = ComplexTypesDeeplyNestedErrors[keyof ComplexTypesDeeplyNestedErrors];

export type ComplexTypesDeeplyNestedResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                level1: {
                    level2: {
                        level3: {
                            value: string;
                        };
                    };
                };
            };
        };
    };
};

export type ComplexTypesDeeplyNestedResponse = ComplexTypesDeeplyNestedResponses[keyof ComplexTypesDeeplyNestedResponses];

export type ComplexTypesDateTypeData = {
    body?: never;
    path?: never;
    query: {
        input: {
            createdAt: Date;
        };
    };
    url: '/complexTypes.dateType';
};

export type ComplexTypesDateTypeErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesDateTypeError = ComplexTypesDateTypeErrors[keyof ComplexTypesDateTypeErrors];

export type ComplexTypesDateTypeResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                createdAt: Date;
            };
        };
    };
};

export type ComplexTypesDateTypeResponse = ComplexTypesDateTypeResponses[keyof ComplexTypesDateTypeResponses];

export type ComplexTypesAnyAndUnknownData = {
    body?: never;
    path?: never;
    query: {
        input: {
            anything: unknown;
            something: unknown;
        };
    };
    url: '/complexTypes.anyAndUnknown';
};

export type ComplexTypesAnyAndUnknownErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesAnyAndUnknownError = ComplexTypesAnyAndUnknownErrors[keyof ComplexTypesAnyAndUnknownErrors];

export type ComplexTypesAnyAndUnknownResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                anything: unknown;
                something: unknown;
            };
        };
    };
};

export type ComplexTypesAnyAndUnknownResponse = ComplexTypesAnyAndUnknownResponses[keyof ComplexTypesAnyAndUnknownResponses];

export type ComplexTypesDefaultsData = {
    body?: never;
    path?: never;
    query: {
        input: {
            page?: number;
            limit?: number;
            sort?: 'asc' | 'desc';
        };
    };
    url: '/complexTypes.defaults';
};

export type ComplexTypesDefaultsErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesDefaultsError = ComplexTypesDefaultsErrors[keyof ComplexTypesDefaultsErrors];

export type ComplexTypesDefaultsResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                page: number;
                limit: number;
                sort: 'asc' | 'desc';
            };
        };
    };
};

export type ComplexTypesDefaultsResponse = ComplexTypesDefaultsResponses[keyof ComplexTypesDefaultsResponses];

export type ComplexTypesRefinedData = {
    body?: never;
    path?: never;
    query: {
        input: {
            email: string;
            age: number;
            url: string;
        };
    };
    url: '/complexTypes.refined';
};

export type ComplexTypesRefinedErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesRefinedError = ComplexTypesRefinedErrors[keyof ComplexTypesRefinedErrors];

export type ComplexTypesRefinedResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                email: string;
                age: number;
                url: string;
            };
        };
    };
};

export type ComplexTypesRefinedResponse = ComplexTypesRefinedResponses[keyof ComplexTypesRefinedResponses];

export type ComplexTypesNullableUnionData = {
    body?: never;
    path?: never;
    query: {
        input: {
            value: string | number | null;
            optionalValue?: string | number;
        };
    };
    url: '/complexTypes.nullableUnion';
};

export type ComplexTypesNullableUnionErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesNullableUnionError = ComplexTypesNullableUnionErrors[keyof ComplexTypesNullableUnionErrors];

export type ComplexTypesNullableUnionResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                value: string | number | null;
                optionalValue?: string | number;
            };
        };
    };
};

export type ComplexTypesNullableUnionResponse = ComplexTypesNullableUnionResponses[keyof ComplexTypesNullableUnionResponses];

export type ComplexTypesPassthroughData = {
    body?: never;
    path?: never;
    query: {
        input: {
            known: string;
            [key: string]: unknown;
        };
    };
    url: '/complexTypes.passthrough';
};

export type ComplexTypesPassthroughErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesPassthroughError = ComplexTypesPassthroughErrors[keyof ComplexTypesPassthroughErrors];

export type ComplexTypesPassthroughResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                known: string;
                [key: string]: unknown;
            };
        };
    };
};

export type ComplexTypesPassthroughResponse = ComplexTypesPassthroughResponses[keyof ComplexTypesPassthroughResponses];

export type ComplexTypesStrictData = {
    body?: never;
    path?: never;
    query: {
        input: {
            known: string;
        };
    };
    url: '/complexTypes.strict';
};

export type ComplexTypesStrictErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesStrictError = ComplexTypesStrictErrors[keyof ComplexTypesStrictErrors];

export type ComplexTypesStrictResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                known: string;
            };
        };
    };
};

export type ComplexTypesStrictResponse = ComplexTypesStrictResponses[keyof ComplexTypesStrictResponses];

export type ComplexTypesBrandedData = {
    body?: never;
    path?: never;
    query: {
        input: {
            userId: string;
        };
    };
    url: '/complexTypes.branded';
};

export type ComplexTypesBrandedErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesBrandedError = ComplexTypesBrandedErrors[keyof ComplexTypesBrandedErrors];

export type ComplexTypesBrandedResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                userId: string;
            };
        };
    };
};

export type ComplexTypesBrandedResponse = ComplexTypesBrandedResponses[keyof ComplexTypesBrandedResponses];

export type ComplexTypesWithCatchData = {
    body?: never;
    path?: never;
    query: {
        input: {
            status: 'on' | 'off';
        };
    };
    url: '/complexTypes.withCatch';
};

export type ComplexTypesWithCatchErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesWithCatchError = ComplexTypesWithCatchErrors[keyof ComplexTypesWithCatchErrors];

export type ComplexTypesWithCatchResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                status: 'on' | 'off';
            };
        };
    };
};

export type ComplexTypesWithCatchResponse = ComplexTypesWithCatchResponses[keyof ComplexTypesWithCatchResponses];

export type ComplexTypesPipedData = {
    body?: never;
    path?: never;
    query: {
        input: {
            value: string;
        };
    };
    url: '/complexTypes.piped';
};

export type ComplexTypesPipedErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesPipedError = ComplexTypesPipedErrors[keyof ComplexTypesPipedErrors];

export type ComplexTypesPipedResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                value: number;
            };
        };
    };
};

export type ComplexTypesPipedResponse = ComplexTypesPipedResponses[keyof ComplexTypesPipedResponses];

export type ComplexTypesCreateContentData = {
    body: {
        title: string;
        body: string;
        tags?: Array<string>;
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/complexTypes.createContent';
};

export type ComplexTypesCreateContentErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesCreateContentError = ComplexTypesCreateContentErrors[keyof ComplexTypesCreateContentErrors];

export type ComplexTypesCreateContentResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                status: 'success';
                id: number;
                createdAt: string;
            } | {
                status: 'error';
                message: string;
                code: number;
            };
        };
    };
};

export type ComplexTypesCreateContentResponse = ComplexTypesCreateContentResponses[keyof ComplexTypesCreateContentResponses];

export type ComplexTypesSearchData = {
    body?: never;
    path?: never;
    query: {
        input: {
            query: string;
            filters?: {
                category?: 'all' | 'posts' | 'users' | 'comments';
                dateRange?: {
                    from: string;
                    to: string;
                };
                tags?: Array<string>;
                sortBy?: 'date' | 'relevance' | 'popularity';
            };
            pagination?: {
                page: number;
                limit: number;
            };
        };
    };
    url: '/complexTypes.search';
};

export type ComplexTypesSearchErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexTypesSearchError = ComplexTypesSearchErrors[keyof ComplexTypesSearchErrors];

export type ComplexTypesSearchResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                results: Array<{
                    id: string;
                    title: string;
                    snippet: string;
                    score: number;
                }>;
                total: number;
                hasMore: boolean;
            };
        };
    };
};

export type ComplexTypesSearchResponse = ComplexTypesSearchResponses[keyof ComplexTypesSearchResponses];

export type InferredReturnsEnumLikeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.enumLike';
};

export type InferredReturnsEnumLikeErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsEnumLikeError = InferredReturnsEnumLikeErrors[keyof InferredReturnsEnumLikeErrors];

export type InferredReturnsEnumLikeResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                status: 'active' | 'inactive' | 'pending';
            };
        };
    };
};

export type InferredReturnsEnumLikeResponse = InferredReturnsEnumLikeResponses[keyof InferredReturnsEnumLikeResponses];

export type InferredReturnsStringLiteralData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.stringLiteral';
};

export type InferredReturnsStringLiteralErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsStringLiteralError = InferredReturnsStringLiteralErrors[keyof InferredReturnsStringLiteralErrors];

export type InferredReturnsStringLiteralResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: 'hello';
        };
    };
};

export type InferredReturnsStringLiteralResponse = InferredReturnsStringLiteralResponses[keyof InferredReturnsStringLiteralResponses];

export type InferredReturnsNumberLiteralData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.numberLiteral';
};

export type InferredReturnsNumberLiteralErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsNumberLiteralError = InferredReturnsNumberLiteralErrors[keyof InferredReturnsNumberLiteralErrors];

export type InferredReturnsNumberLiteralResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: 42;
        };
    };
};

export type InferredReturnsNumberLiteralResponse = InferredReturnsNumberLiteralResponses[keyof InferredReturnsNumberLiteralResponses];

export type InferredReturnsBooleanLiteralData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.booleanLiteral';
};

export type InferredReturnsBooleanLiteralErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsBooleanLiteralError = InferredReturnsBooleanLiteralErrors[keyof InferredReturnsBooleanLiteralErrors];

export type InferredReturnsBooleanLiteralResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: true;
        };
    };
};

export type InferredReturnsBooleanLiteralResponse = InferredReturnsBooleanLiteralResponses[keyof InferredReturnsBooleanLiteralResponses];

export type InferredReturnsDiscriminatedResultData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.discriminatedResult';
};

export type InferredReturnsDiscriminatedResultErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsDiscriminatedResultError = InferredReturnsDiscriminatedResultErrors[keyof InferredReturnsDiscriminatedResultErrors];

export type InferredReturnsDiscriminatedResultResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                type: 'success';
                id: number;
                createdAt: string;
                message?: unknown;
                code?: unknown;
            } | {
                type: 'error';
                message: string;
                code: number;
                id?: unknown;
                createdAt?: unknown;
            };
        };
    };
};

export type InferredReturnsDiscriminatedResultResponse = InferredReturnsDiscriminatedResultResponses[keyof InferredReturnsDiscriminatedResultResponses];

export type InferredReturnsPrimitiveUnionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.primitiveUnion';
};

export type InferredReturnsPrimitiveUnionErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsPrimitiveUnionError = InferredReturnsPrimitiveUnionErrors[keyof InferredReturnsPrimitiveUnionErrors];

export type InferredReturnsPrimitiveUnionResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                value: string | number | boolean;
            };
        };
    };
};

export type InferredReturnsPrimitiveUnionResponse = InferredReturnsPrimitiveUnionResponses[keyof InferredReturnsPrimitiveUnionResponses];

export type InferredReturnsTupleReturnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.tupleReturn';
};

export type InferredReturnsTupleReturnErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsTupleReturnError = InferredReturnsTupleReturnErrors[keyof InferredReturnsTupleReturnErrors];

export type InferredReturnsTupleReturnResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: [
                string,
                number
            ];
        };
    };
};

export type InferredReturnsTupleReturnResponse = InferredReturnsTupleReturnResponses[keyof InferredReturnsTupleReturnResponses];

export type InferredReturnsRecordReturnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.recordReturn';
};

export type InferredReturnsRecordReturnErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsRecordReturnError = InferredReturnsRecordReturnErrors[keyof InferredReturnsRecordReturnErrors];

export type InferredReturnsRecordReturnResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                [key: string]: number;
            };
        };
    };
};

export type InferredReturnsRecordReturnResponse = InferredReturnsRecordReturnResponses[keyof InferredReturnsRecordReturnResponses];

export type InferredReturnsArrayOfObjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.arrayOfObjects';
};

export type InferredReturnsArrayOfObjectsErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsArrayOfObjectsError = InferredReturnsArrayOfObjectsErrors[keyof InferredReturnsArrayOfObjectsErrors];

export type InferredReturnsArrayOfObjectsResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: Array<{
                id: number;
                name: string;
                active: boolean;
            }>;
        };
    };
};

export type InferredReturnsArrayOfObjectsResponse = InferredReturnsArrayOfObjectsResponses[keyof InferredReturnsArrayOfObjectsResponses];

export type InferredReturnsMatrixData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.matrix';
};

export type InferredReturnsMatrixErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsMatrixError = InferredReturnsMatrixErrors[keyof InferredReturnsMatrixErrors];

export type InferredReturnsMatrixResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: Array<Array<number>>;
        };
    };
};

export type InferredReturnsMatrixResponse = InferredReturnsMatrixResponses[keyof InferredReturnsMatrixResponses];

export type InferredReturnsDeeplyNestedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.deeplyNested';
};

export type InferredReturnsDeeplyNestedErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsDeeplyNestedError = InferredReturnsDeeplyNestedErrors[keyof InferredReturnsDeeplyNestedErrors];

export type InferredReturnsDeeplyNestedResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                level1: {
                    level2: {
                        level3: {
                            value: string;
                        };
                    };
                };
            };
        };
    };
};

export type InferredReturnsDeeplyNestedResponse = InferredReturnsDeeplyNestedResponses[keyof InferredReturnsDeeplyNestedResponses];

export type InferredReturnsDateReturnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.dateReturn';
};

export type InferredReturnsDateReturnErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsDateReturnError = InferredReturnsDateReturnErrors[keyof InferredReturnsDateReturnErrors];

export type InferredReturnsDateReturnResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                createdAt: Date;
            };
        };
    };
};

export type InferredReturnsDateReturnResponse = InferredReturnsDateReturnResponses[keyof InferredReturnsDateReturnResponses];

export type InferredReturnsNullableReturnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.nullableReturn';
};

export type InferredReturnsNullableReturnErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsNullableReturnError = InferredReturnsNullableReturnErrors[keyof InferredReturnsNullableReturnErrors];

export type InferredReturnsNullableReturnResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                value: string | null;
            };
        };
    };
};

export type InferredReturnsNullableReturnResponse = InferredReturnsNullableReturnResponses[keyof InferredReturnsNullableReturnResponses];

export type InferredReturnsOptionalFieldsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.optionalFields';
};

export type InferredReturnsOptionalFieldsErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsOptionalFieldsError = InferredReturnsOptionalFieldsErrors[keyof InferredReturnsOptionalFieldsErrors];

export type InferredReturnsOptionalFieldsResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                name: string;
                age?: number;
                email?: string;
            };
        };
    };
};

export type InferredReturnsOptionalFieldsResponse = InferredReturnsOptionalFieldsResponses[keyof InferredReturnsOptionalFieldsResponses];

export type InferredReturnsMixedObjectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.mixedObject';
};

export type InferredReturnsMixedObjectErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsMixedObjectError = InferredReturnsMixedObjectErrors[keyof InferredReturnsMixedObjectErrors];

export type InferredReturnsMixedObjectResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                id: number;
                name: string;
                tags: Array<string>;
                metadata: {
                    [key: string]: string;
                };
                active: boolean;
                score: number;
            };
        };
    };
};

export type InferredReturnsMixedObjectResponse = InferredReturnsMixedObjectResponses[keyof InferredReturnsMixedObjectResponses];

export type InferredReturnsVoidReturnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.voidReturn';
};

export type InferredReturnsVoidReturnErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsVoidReturnError = InferredReturnsVoidReturnErrors[keyof InferredReturnsVoidReturnErrors];

export type InferredReturnsVoidReturnResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            [key: string]: unknown;
        };
    };
};

export type InferredReturnsVoidReturnResponse = InferredReturnsVoidReturnResponses[keyof InferredReturnsVoidReturnResponses];

export type InferredReturnsNullReturnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.nullReturn';
};

export type InferredReturnsNullReturnErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsNullReturnError = InferredReturnsNullReturnErrors[keyof InferredReturnsNullReturnErrors];

export type InferredReturnsNullReturnResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: null;
        };
    };
};

export type InferredReturnsNullReturnResponse = InferredReturnsNullReturnResponses[keyof InferredReturnsNullReturnResponses];

export type InferredReturnsMergedObjectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.mergedObject';
};

export type InferredReturnsMergedObjectErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsMergedObjectError = InferredReturnsMergedObjectErrors[keyof InferredReturnsMergedObjectErrors];

export type InferredReturnsMergedObjectResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                name: string;
                email: string;
                id: number;
            };
        };
    };
};

export type InferredReturnsMergedObjectResponse = InferredReturnsMergedObjectResponses[keyof InferredReturnsMergedObjectResponses];

export type InferredReturnsLiteralArrayData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.literalArray';
};

export type InferredReturnsLiteralArrayErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsLiteralArrayError = InferredReturnsLiteralArrayErrors[keyof InferredReturnsLiteralArrayErrors];

export type InferredReturnsLiteralArrayResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: [
                'red',
                'green',
                'blue'
            ];
        };
    };
};

export type InferredReturnsLiteralArrayResponse = InferredReturnsLiteralArrayResponses[keyof InferredReturnsLiteralArrayResponses];

export type InferredReturnsNestedNullableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.nestedNullable';
};

export type InferredReturnsNestedNullableErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsNestedNullableError = InferredReturnsNestedNullableErrors[keyof InferredReturnsNestedNullableErrors];

export type InferredReturnsNestedNullableResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                outer: {
                    inner: string | null;
                    maybeNum?: number;
                } | null;
            };
        };
    };
};

export type InferredReturnsNestedNullableResponse = InferredReturnsNestedNullableResponses[keyof InferredReturnsNestedNullableResponses];

export type InferredReturnsBoolReturnFalseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.boolReturnFalse';
};

export type InferredReturnsBoolReturnFalseErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsBoolReturnFalseError = InferredReturnsBoolReturnFalseErrors[keyof InferredReturnsBoolReturnFalseErrors];

export type InferredReturnsBoolReturnFalseResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: false;
        };
    };
};

export type InferredReturnsBoolReturnFalseResponse = InferredReturnsBoolReturnFalseResponses[keyof InferredReturnsBoolReturnFalseResponses];

export type InferredReturnsBoolReturnTrueData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.boolReturnTrue';
};

export type InferredReturnsBoolReturnTrueErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsBoolReturnTrueError = InferredReturnsBoolReturnTrueErrors[keyof InferredReturnsBoolReturnTrueErrors];

export type InferredReturnsBoolReturnTrueResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: true;
        };
    };
};

export type InferredReturnsBoolReturnTrueResponse = InferredReturnsBoolReturnTrueResponses[keyof InferredReturnsBoolReturnTrueResponses];

export type InferredReturnsBoolReturnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.boolReturn';
};

export type InferredReturnsBoolReturnErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsBoolReturnError = InferredReturnsBoolReturnErrors[keyof InferredReturnsBoolReturnErrors];

export type InferredReturnsBoolReturnResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: boolean;
        };
    };
};

export type InferredReturnsBoolReturnResponse = InferredReturnsBoolReturnResponses[keyof InferredReturnsBoolReturnResponses];

export type InferredReturnsNumReturnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.numReturn';
};

export type InferredReturnsNumReturnErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsNumReturnError = InferredReturnsNumReturnErrors[keyof InferredReturnsNumReturnErrors];

export type InferredReturnsNumReturnResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: number;
        };
    };
};

export type InferredReturnsNumReturnResponse = InferredReturnsNumReturnResponses[keyof InferredReturnsNumReturnResponses];

export type InferredReturnsStrReturnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.strReturn';
};

export type InferredReturnsStrReturnErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsStrReturnError = InferredReturnsStrReturnErrors[keyof InferredReturnsStrReturnErrors];

export type InferredReturnsStrReturnResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: string;
        };
    };
};

export type InferredReturnsStrReturnResponse = InferredReturnsStrReturnResponses[keyof InferredReturnsStrReturnResponses];

export type InferredReturnsCreateItemData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/inferredReturns.createItem';
};

export type InferredReturnsCreateItemErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsCreateItemError = InferredReturnsCreateItemErrors[keyof InferredReturnsCreateItemErrors];

export type InferredReturnsCreateItemResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                id: number;
                name: string;
                createdAt: Date;
                status: 'created';
                tags: Array<string>;
                metadata: {
                    [key: string]: string;
                } | null;
            };
        };
    };
};

export type InferredReturnsCreateItemResponse = InferredReturnsCreateItemResponses[keyof InferredReturnsCreateItemResponses];

export type InferredReturnsStringEnumData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.stringEnum';
};

export type InferredReturnsStringEnumErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsStringEnumError = InferredReturnsStringEnumErrors[keyof InferredReturnsStringEnumErrors];

export type InferredReturnsStringEnumResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                direction: 'UP' | 'DOWN' | 'LEFT' | 'RIGHT';
            };
        };
    };
};

export type InferredReturnsStringEnumResponse = InferredReturnsStringEnumResponses[keyof InferredReturnsStringEnumResponses];

export type InferredReturnsNumericEnumData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.numericEnum';
};

export type InferredReturnsNumericEnumErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsNumericEnumError = InferredReturnsNumericEnumErrors[keyof InferredReturnsNumericEnumErrors];

export type InferredReturnsNumericEnumResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                status: 1 | 2 | 3;
            };
        };
    };
};

export type InferredReturnsNumericEnumResponse = InferredReturnsNumericEnumResponses[keyof InferredReturnsNumericEnumResponses];

export type InferredReturnsMixedEnumData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.mixedEnum';
};

export type InferredReturnsMixedEnumErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsMixedEnumError = InferredReturnsMixedEnumErrors[keyof InferredReturnsMixedEnumErrors];

export type InferredReturnsMixedEnumResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                value: 'FOO' | 1 | 'BAZ';
            };
        };
    };
};

export type InferredReturnsMixedEnumResponse = InferredReturnsMixedEnumResponses[keyof InferredReturnsMixedEnumResponses];

export type InferredReturnsBrandedReturnsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/inferredReturns.brandedReturns';
};

export type InferredReturnsBrandedReturnsErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type InferredReturnsBrandedReturnsError = InferredReturnsBrandedReturnsErrors[keyof InferredReturnsBrandedReturnsErrors];

export type InferredReturnsBrandedReturnsResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                userId: string;
                score: number;
                active: boolean;
            };
        };
    };
};

export type InferredReturnsBrandedReturnsResponse = InferredReturnsBrandedReturnsResponses[keyof InferredReturnsBrandedReturnsResponses];

export type NamedTypesWithProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/namedTypes.withProfile';
};

export type NamedTypesWithProfileErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type NamedTypesWithProfileError = NamedTypesWithProfileErrors[keyof NamedTypesWithProfileErrors];

export type NamedTypesWithProfileResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                profile: UserProfile;
            };
        };
    };
};

export type NamedTypesWithProfileResponse = NamedTypesWithProfileResponses[keyof NamedTypesWithProfileResponses];

export type NamedTypesOrderItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/namedTypes.orderItems';
};

export type NamedTypesOrderItemsErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type NamedTypesOrderItemsError = NamedTypesOrderItemsErrors[keyof NamedTypesOrderItemsErrors];

export type NamedTypesOrderItemsResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                items: Array<OrderItem>;
            };
        };
    };
};

export type NamedTypesOrderItemsResponse = NamedTypesOrderItemsResponses[keyof NamedTypesOrderItemsResponses];

export type NamedTypesWithAddressData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/namedTypes.withAddress';
};

export type NamedTypesWithAddressErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type NamedTypesWithAddressError = NamedTypesWithAddressErrors[keyof NamedTypesWithAddressErrors];

export type NamedTypesWithAddressResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                address: Address;
            };
        };
    };
};

export type NamedTypesWithAddressResponse = NamedTypesWithAddressResponses[keyof NamedTypesWithAddressResponses];

export type NamedTypesProfileAndAddressData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/namedTypes.profileAndAddress';
};

export type NamedTypesProfileAndAddressErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type NamedTypesProfileAndAddressError = NamedTypesProfileAndAddressErrors[keyof NamedTypesProfileAndAddressErrors];

export type NamedTypesProfileAndAddressResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                profile: UserProfile;
                address: Address;
            };
        };
    };
};

export type NamedTypesProfileAndAddressResponse = NamedTypesProfileAndAddressResponses[keyof NamedTypesProfileAndAddressResponses];

export type NamedTypesDeepNestedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/namedTypes.deepNested';
};

export type NamedTypesDeepNestedErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type NamedTypesDeepNestedError = NamedTypesDeepNestedErrors[keyof NamedTypesDeepNestedErrors];

export type NamedTypesDeepNestedResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                data: {
                    nested: {
                        profile: UserProfile;
                    };
                };
            };
        };
    };
};

export type NamedTypesDeepNestedResponse = NamedTypesDeepNestedResponses[keyof NamedTypesDeepNestedResponses];

export type RecursiveTypesTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/recursiveTypes.tree';
};

export type RecursiveTypesTreeErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type RecursiveTypesTreeError = RecursiveTypesTreeErrors[keyof RecursiveTypesTreeErrors];

export type RecursiveTypesTreeResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: TreeNode;
        };
    };
};

export type RecursiveTypesTreeResponse = RecursiveTypesTreeResponses[keyof RecursiveTypesTreeResponses];

export type RecursiveTypesLinkedListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/recursiveTypes.linkedList';
};

export type RecursiveTypesLinkedListErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type RecursiveTypesLinkedListError = RecursiveTypesLinkedListErrors[keyof RecursiveTypesLinkedListErrors];

export type RecursiveTypesLinkedListResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: LinkedListNode;
        };
    };
};

export type RecursiveTypesLinkedListResponse = RecursiveTypesLinkedListResponses[keyof RecursiveTypesLinkedListResponses];

export type RecursiveTypesCategoryData = {
    body?: never;
    path?: never;
    query: {
        input: unknown;
    };
    url: '/recursiveTypes.category';
};

export type RecursiveTypesCategoryErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type RecursiveTypesCategoryError = RecursiveTypesCategoryErrors[keyof RecursiveTypesCategoryErrors];

export type RecursiveTypesCategoryResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: Category;
        };
    };
};

export type RecursiveTypesCategoryResponse = RecursiveTypesCategoryResponses[keyof RecursiveTypesCategoryResponses];

export type SimpleCasesNullishData = {
    body?: never;
    path?: never;
    query: {
        input: {
            name?: string | null;
        } | null;
    };
    url: '/simpleCases.nullish';
};

export type SimpleCasesNullishErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type SimpleCasesNullishError = SimpleCasesNullishErrors[keyof SimpleCasesNullishErrors];

export type SimpleCasesNullishResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                name?: string | null;
            } | null;
        };
    };
};

export type SimpleCasesNullishResponse = SimpleCasesNullishResponses[keyof SimpleCasesNullishResponses];

export type SimpleCasesOptionalData = {
    body?: never;
    path?: never;
    query: {
        input: {
            name?: string;
        };
    };
    url: '/simpleCases.optional';
};

export type SimpleCasesOptionalErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type SimpleCasesOptionalError = SimpleCasesOptionalErrors[keyof SimpleCasesOptionalErrors];

export type SimpleCasesOptionalResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                name?: string;
            };
        };
    };
};

export type SimpleCasesOptionalResponse = SimpleCasesOptionalResponses[keyof SimpleCasesOptionalResponses];

export type SimpleCasesNullableData = {
    body?: never;
    path?: never;
    query: {
        input: {
            name: string | null;
        } | null;
    };
    url: '/simpleCases.nullable';
};

export type SimpleCasesNullableErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type SimpleCasesNullableError = SimpleCasesNullableErrors[keyof SimpleCasesNullableErrors];

export type SimpleCasesNullableResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                name: string | null;
            } | null;
        };
    };
};

export type SimpleCasesNullableResponse = SimpleCasesNullableResponses[keyof SimpleCasesNullableResponses];
