// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AsyncReturnData, AsyncReturnErrors, AsyncReturnResponses, BigintData, BigintErrors, BigintResponses, BinaryData, BinaryErrors, BinaryResponses, BoolNullableData, BoolNullableErrors, BoolNullableResponses, BoolUnionData, BoolUnionErrors, BoolUnionResponses, ComplexNullableData, ComplexNullableErrors, ComplexNullableResponses, Level1Level2Level3DeepData, Level1Level2Level3DeepErrors, Level1Level2Level3DeepResponses, NeverFieldData, NeverFieldErrors, NeverFieldResponses, NoInputMutationData, NoInputMutationErrors, NoInputMutationResponses, NullableObjectData, NullableObjectErrors, NullableObjectResponses, NullOnlyData, NullOnlyErrors, NullOnlyResponses, SimpleQueryData, SimpleQueryErrors, SimpleQueryResponses, UndefinedInputData, UndefinedInputErrors, UndefinedInputResponses, VoidExplicitData, VoidExplicitErrors, VoidExplicitResponses, VoidInputData, VoidInputErrors, VoidInputResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new Sdk()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class Level3 extends HeyApiClient {
    public deep<ThrowOnError extends boolean = false>(options?: Options<Level1Level2Level3DeepData, ThrowOnError>) {
        return (options?.client ?? this.client).get<Level1Level2Level3DeepResponses, Level1Level2Level3DeepErrors, ThrowOnError>({ url: '/level1.level2.level3.deep', ...options });
    }
}

export class Level2 extends HeyApiClient {
    private _level3?: Level3;
    get level3(): Level3 {
        return this._level3 ??= new Level3({ client: this.client });
    }
}

export class Level1 extends HeyApiClient {
    private _level2?: Level2;
    get level2(): Level2 {
        return this._level2 ??= new Level2({ client: this.client });
    }
}

export class Sdk extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<Sdk>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        Sdk.__registry.set(this, args?.key);
    }
    
    public bigint<ThrowOnError extends boolean = false>(options?: Options<BigintData, ThrowOnError>) {
        return (options?.client ?? this.client).get<BigintResponses, BigintErrors, ThrowOnError>({ url: '/bigint', ...options });
    }
    
    public neverField<ThrowOnError extends boolean = false>(options?: Options<NeverFieldData, ThrowOnError>) {
        return (options?.client ?? this.client).get<NeverFieldResponses, NeverFieldErrors, ThrowOnError>({ url: '/neverField', ...options });
    }
    
    public asyncReturn<ThrowOnError extends boolean = false>(options?: Options<AsyncReturnData, ThrowOnError>) {
        return (options?.client ?? this.client).get<AsyncReturnResponses, AsyncReturnErrors, ThrowOnError>({ url: '/asyncReturn', ...options });
    }
    
    public voidInput<ThrowOnError extends boolean = false>(options?: Options<VoidInputData, ThrowOnError>) {
        return (options?.client ?? this.client).get<VoidInputResponses, VoidInputErrors, ThrowOnError>({ url: '/voidInput', ...options });
    }
    
    public undefinedInput<ThrowOnError extends boolean = false>(options?: Options<UndefinedInputData, ThrowOnError>) {
        return (options?.client ?? this.client).get<UndefinedInputResponses, UndefinedInputErrors, ThrowOnError>({ url: '/undefinedInput', ...options });
    }
    
    public voidExplicit<ThrowOnError extends boolean = false>(options?: Options<VoidExplicitData, ThrowOnError>) {
        return (options?.client ?? this.client).get<VoidExplicitResponses, VoidExplicitErrors, ThrowOnError>({ url: '/voidExplicit', ...options });
    }
    
    public simpleQuery<ThrowOnError extends boolean = false>(options?: Options<SimpleQueryData, ThrowOnError>) {
        return (options?.client ?? this.client).get<SimpleQueryResponses, SimpleQueryErrors, ThrowOnError>({ url: '/simpleQuery', ...options });
    }
    
    public boolUnion<ThrowOnError extends boolean = false>(options?: Options<BoolUnionData, ThrowOnError>) {
        return (options?.client ?? this.client).get<BoolUnionResponses, BoolUnionErrors, ThrowOnError>({ url: '/boolUnion', ...options });
    }
    
    public boolNullable<ThrowOnError extends boolean = false>(options?: Options<BoolNullableData, ThrowOnError>) {
        return (options?.client ?? this.client).get<BoolNullableResponses, BoolNullableErrors, ThrowOnError>({ url: '/boolNullable', ...options });
    }
    
    public nullOnly<ThrowOnError extends boolean = false>(options?: Options<NullOnlyData, ThrowOnError>) {
        return (options?.client ?? this.client).get<NullOnlyResponses, NullOnlyErrors, ThrowOnError>({ url: '/nullOnly', ...options });
    }
    
    public binary<ThrowOnError extends boolean = false>(options?: Options<BinaryData, ThrowOnError>) {
        return (options?.client ?? this.client).get<BinaryResponses, BinaryErrors, ThrowOnError>({ url: '/binary', ...options });
    }
    
    public nullableObject<ThrowOnError extends boolean = false>(options?: Options<NullableObjectData, ThrowOnError>) {
        return (options?.client ?? this.client).get<NullableObjectResponses, NullableObjectErrors, ThrowOnError>({ url: '/nullableObject', ...options });
    }
    
    public noInputMutation<ThrowOnError extends boolean = false>(options?: Options<NoInputMutationData, ThrowOnError>) {
        return (options?.client ?? this.client).post<NoInputMutationResponses, NoInputMutationErrors, ThrowOnError>({ url: '/noInputMutation', ...options });
    }
    
    public complexNullable<ThrowOnError extends boolean = false>(options?: Options<ComplexNullableData, ThrowOnError>) {
        return (options?.client ?? this.client).get<ComplexNullableResponses, ComplexNullableErrors, ThrowOnError>({ url: '/complexNullable', ...options });
    }
    
    private _level1?: Level1;
    get level1(): Level1 {
        return this._level1 ??= new Level1({ client: this.client });
    }
}
