// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type WithBigInt = {
    id: number;
};

export type NeverField = {
    valid: string;
    impossible?: unknown;
};

export type AsyncIterable = {
    '__@asyncIterator@2986': {
        [key: string]: unknown;
    };
};

export type DefaultErrorShape = {
    message: string;
    code: -32700 | -32600 | -32603 | -32001 | -32002 | -32003 | -32004 | -32005 | -32008 | -32009 | -32012 | -32013 | -32015 | -32022 | -32028 | -32029 | -32099;
    data: DefaultErrorData;
};

export type DefaultErrorData = {
    code: 'PARSE_ERROR' | 'BAD_REQUEST' | 'INTERNAL_SERVER_ERROR' | 'NOT_IMPLEMENTED' | 'BAD_GATEWAY' | 'SERVICE_UNAVAILABLE' | 'GATEWAY_TIMEOUT' | 'UNAUTHORIZED' | 'PAYMENT_REQUIRED' | 'FORBIDDEN' | 'NOT_FOUND' | 'METHOD_NOT_SUPPORTED' | 'TIMEOUT' | 'CONFLICT' | 'PRECONDITION_FAILED' | 'PAYLOAD_TOO_LARGE' | 'UNSUPPORTED_MEDIA_TYPE' | 'UNPROCESSABLE_CONTENT' | 'PRECONDITION_REQUIRED' | 'TOO_MANY_REQUESTS' | 'CLIENT_CLOSED_REQUEST';
    httpStatus: number;
    path?: string;
    stack?: string;
};

export type BigintData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bigint';
};

export type BigintErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type BigintError = BigintErrors[keyof BigintErrors];

export type BigintResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: WithBigInt;
        };
    };
};

export type BigintResponse = BigintResponses[keyof BigintResponses];

export type NeverFieldData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/neverField';
};

export type NeverFieldErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type NeverFieldError = NeverFieldErrors[keyof NeverFieldErrors];

export type NeverFieldResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: NeverField;
        };
    };
};

export type NeverFieldResponse = NeverFieldResponses[keyof NeverFieldResponses];

export type AsyncReturnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/asyncReturn';
};

export type AsyncReturnErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type AsyncReturnError = AsyncReturnErrors[keyof AsyncReturnErrors];

export type AsyncReturnResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                data: string;
            };
        };
    };
};

export type AsyncReturnResponse = AsyncReturnResponses[keyof AsyncReturnResponses];

export type VoidInputData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/voidInput';
};

export type VoidInputErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type VoidInputError = VoidInputErrors[keyof VoidInputErrors];

export type VoidInputResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: string;
        };
    };
};

export type VoidInputResponse = VoidInputResponses[keyof VoidInputResponses];

export type UndefinedInputData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/undefinedInput';
};

export type UndefinedInputErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type UndefinedInputError = UndefinedInputErrors[keyof UndefinedInputErrors];

export type UndefinedInputResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: string;
        };
    };
};

export type UndefinedInputResponse = UndefinedInputResponses[keyof UndefinedInputResponses];

export type VoidExplicitData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/voidExplicit';
};

export type VoidExplicitErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type VoidExplicitError = VoidExplicitErrors[keyof VoidExplicitErrors];

export type VoidExplicitResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: string;
        };
    };
};

export type VoidExplicitResponse = VoidExplicitResponses[keyof VoidExplicitResponses];

export type SimpleQueryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/simpleQuery';
};

export type SimpleQueryErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type SimpleQueryError = SimpleQueryErrors[keyof SimpleQueryErrors];

export type SimpleQueryResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: number;
        };
    };
};

export type SimpleQueryResponse = SimpleQueryResponses[keyof SimpleQueryResponses];

export type Level1Level2Level3DeepData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/level1.level2.level3.deep';
};

export type Level1Level2Level3DeepErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type Level1Level2Level3DeepError = Level1Level2Level3DeepErrors[keyof Level1Level2Level3DeepErrors];

export type Level1Level2Level3DeepResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: string;
        };
    };
};

export type Level1Level2Level3DeepResponse = Level1Level2Level3DeepResponses[keyof Level1Level2Level3DeepResponses];

export type BoolUnionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/boolUnion';
};

export type BoolUnionErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type BoolUnionError = BoolUnionErrors[keyof BoolUnionErrors];

export type BoolUnionResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                flag: boolean;
            };
        };
    };
};

export type BoolUnionResponse = BoolUnionResponses[keyof BoolUnionResponses];

export type BoolNullableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/boolNullable';
};

export type BoolNullableErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type BoolNullableError = BoolNullableErrors[keyof BoolNullableErrors];

export type BoolNullableResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                flag: boolean | null;
            };
        };
    };
};

export type BoolNullableResponse = BoolNullableResponses[keyof BoolNullableResponses];

export type NullOnlyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nullOnly';
};

export type NullOnlyErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type NullOnlyError = NullOnlyErrors[keyof NullOnlyErrors];

export type NullOnlyResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: null;
        };
    };
};

export type NullOnlyResponse = NullOnlyResponses[keyof NullOnlyResponses];

export type BinaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/binary';
};

export type BinaryErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type BinaryError = BinaryErrors[keyof BinaryErrors];

export type BinaryResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                data: Blob | File;
            };
        };
    };
};

export type BinaryResponse = BinaryResponses[keyof BinaryResponses];

export type NullableObjectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nullableObject';
};

export type NullableObjectErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type NullableObjectError = NullableObjectErrors[keyof NullableObjectErrors];

export type NullableObjectResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                id: number;
                name: string;
            } | null;
        };
    };
};

export type NullableObjectResponse = NullableObjectResponses[keyof NullableObjectResponses];

export type NoInputMutationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/noInputMutation';
};

export type NoInputMutationErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type NoInputMutationError = NoInputMutationErrors[keyof NoInputMutationErrors];

export type NoInputMutationResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                success: boolean;
            };
        };
    };
};

export type NoInputMutationResponse = NoInputMutationResponses[keyof NoInputMutationResponses];

export type ComplexNullableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/complexNullable';
};

export type ComplexNullableErrors = {
    /**
     * Error response
     */
    default: {
        error: DefaultErrorShape;
    };
};

export type ComplexNullableError = ComplexNullableErrors[keyof ComplexNullableErrors];

export type ComplexNullableResponses = {
    /**
     * Successful response
     */
    200: {
        result: {
            data: {
                value: string | number | null;
            };
        };
    };
};

export type ComplexNullableResponse = ComplexNullableResponses[keyof ComplexNullableResponses];
