// This file is auto-generated by @hey-api/openapi-ts

import type { SubrouterInlineHelloResponse } from './types.gen';

const helloInlineResponseSchemaResponseTransformer = (data: any) => {
    data.date = new Date(data.date);
    return data;
};

export const subrouterInlineHelloResponseTransformer = async (data: any): Promise<SubrouterInlineHelloResponse> => {
    data.result.data = helloInlineResponseSchemaResponseTransformer(data.result.data);
    return data;
};
