/**
 * This script takes the outputed types from `prisma-kysely-generator`
 * and puts them + instantiates the Kysely instance into `~/server/db.ts`
 */

import { readFile, rm, writeFile } from 'fs/promises';
import path from 'path';

const generatedFile = path.join(__dirname, 'types/database-types.ts');
const outputFile = path.join(__dirname, '../src/server/db.ts');

(async () => {
  const dbTypes = await readFile(generatedFile, 'utf-8');

  const output = `// Generated by prisma/post-generate.ts

import { Kysely } from "kysely";
import { PlanetScaleDialect } from "kysely-planetscale";

${dbTypes}

export const db = new Kysely<Database>({
  dialect: new PlanetScaleDialect({
    url: process.env.DATABASE_URL,
  }),
});
`;

  await writeFile(outputFile, output, 'utf-8');
  await rm(path.join(__dirname, 'types'), { recursive: true });
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
