// This file is auto-generated by @hey-api/openapi-ts

import type { CreateEventResponse, GetEventResponse } from './types.gen';

export const getEventResponseTransformer = async (
  data: any,
): Promise<GetEventResponse> => {
  data.result.data.at = new Date(data.result.data.at);
  return data;
};

export const createEventResponseTransformer = async (
  data: any,
): Promise<CreateEventResponse> => {
  data.result.data.at = new Date(data.result.data.at);
  return data;
};
