name: Release Packages

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  NPM_CONFIG_PROVENANCE: true

permissions:
  contents: write # For fixing formatting
  id-token: write # For OIDC publishing
  pull-requests: write # For creating release PRs

on:
  workflow_dispatch:
    inputs:
      dist_tag:
        description: 'NPM distribution tag'
        required: true
        type: choice
        default: 'latest'
        options:
          - 'latest'
          - 'canary'
      version_bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - 'patch'
          - 'minor'
  push:
    branches:
      - 'main'
    paths:
      - '.github/setup/*'
      - '.github/workflows/release-manual.yml'
      - 'packages/**'
      - '!packages/**/package.json'
      - '!packages/test/**'

jobs:
  publish:
    if: github.event_name == 'workflow_dispatch' && inputs.dist_tag == 'latest'
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - uses: ./.github/setup
      - run: pnpm add -g npm@latest # For OIDC publishing

      - name: Publish packages
        run: |
          pnpm release:publish ${{ inputs.version_bump }} --dist-tag ${{ inputs.dist_tag }} --yes

  publish-canary:
    if: github.event_name == 'push' || inputs.dist_tag == 'canary'
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - uses: ./.github/setup
      - run: pnpm add -g npm@latest # For OIDC publishing

      - run: pnpm release:publish canary --preid canary --dist-tag canary --yes
